// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="fft_top,hls_ip_2018_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7k160tfbg484-1,HLS_INPUT_CLOCK=3.300000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=2.887500,HLS_SYN_LAT=11265,HLS_SYN_TPT=11266,HLS_SYN_MEM=16,HLS_SYN_DSP=24,HLS_SYN_FF=21363,HLS_SYN_LUT=18172,HLS_VERSION=2018_3}" *)

module fft_top (
        s_axi_ctrl_bus_AWVALID,
        s_axi_ctrl_bus_AWREADY,
        s_axi_ctrl_bus_AWADDR,
        s_axi_ctrl_bus_WVALID,
        s_axi_ctrl_bus_WREADY,
        s_axi_ctrl_bus_WDATA,
        s_axi_ctrl_bus_WSTRB,
        s_axi_ctrl_bus_ARVALID,
        s_axi_ctrl_bus_ARREADY,
        s_axi_ctrl_bus_ARADDR,
        s_axi_ctrl_bus_RVALID,
        s_axi_ctrl_bus_RREADY,
        s_axi_ctrl_bus_RDATA,
        s_axi_ctrl_bus_RRESP,
        s_axi_ctrl_bus_BVALID,
        s_axi_ctrl_bus_BREADY,
        s_axi_ctrl_bus_BRESP,
        ap_clk,
        ap_rst_n,
        interrupt,
        m_axi_mem_bus_AWVALID,
        m_axi_mem_bus_AWREADY,
        m_axi_mem_bus_AWADDR,
        m_axi_mem_bus_AWID,
        m_axi_mem_bus_AWLEN,
        m_axi_mem_bus_AWSIZE,
        m_axi_mem_bus_AWBURST,
        m_axi_mem_bus_AWLOCK,
        m_axi_mem_bus_AWCACHE,
        m_axi_mem_bus_AWPROT,
        m_axi_mem_bus_AWQOS,
        m_axi_mem_bus_AWREGION,
        m_axi_mem_bus_AWUSER,
        m_axi_mem_bus_WVALID,
        m_axi_mem_bus_WREADY,
        m_axi_mem_bus_WDATA,
        m_axi_mem_bus_WSTRB,
        m_axi_mem_bus_WLAST,
        m_axi_mem_bus_WID,
        m_axi_mem_bus_WUSER,
        m_axi_mem_bus_ARVALID,
        m_axi_mem_bus_ARREADY,
        m_axi_mem_bus_ARADDR,
        m_axi_mem_bus_ARID,
        m_axi_mem_bus_ARLEN,
        m_axi_mem_bus_ARSIZE,
        m_axi_mem_bus_ARBURST,
        m_axi_mem_bus_ARLOCK,
        m_axi_mem_bus_ARCACHE,
        m_axi_mem_bus_ARPROT,
        m_axi_mem_bus_ARQOS,
        m_axi_mem_bus_ARREGION,
        m_axi_mem_bus_ARUSER,
        m_axi_mem_bus_RVALID,
        m_axi_mem_bus_RREADY,
        m_axi_mem_bus_RDATA,
        m_axi_mem_bus_RLAST,
        m_axi_mem_bus_RID,
        m_axi_mem_bus_RUSER,
        m_axi_mem_bus_RRESP,
        m_axi_mem_bus_BVALID,
        m_axi_mem_bus_BREADY,
        m_axi_mem_bus_BRESP,
        m_axi_mem_bus_BID,
        m_axi_mem_bus_BUSER
);

parameter    C_S_AXI_CTRL_BUS_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_BUS_ADDR_WIDTH = 7;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_S_AXI_ADDR_WIDTH = 32;
parameter    C_M_AXI_MEM_BUS_ID_WIDTH = 1;
parameter    C_M_AXI_MEM_BUS_ADDR_WIDTH = 32;
parameter    C_M_AXI_MEM_BUS_DATA_WIDTH = 32;
parameter    C_M_AXI_MEM_BUS_AWUSER_WIDTH = 1;
parameter    C_M_AXI_MEM_BUS_ARUSER_WIDTH = 1;
parameter    C_M_AXI_MEM_BUS_WUSER_WIDTH = 1;
parameter    C_M_AXI_MEM_BUS_RUSER_WIDTH = 1;
parameter    C_M_AXI_MEM_BUS_BUSER_WIDTH = 1;
parameter    C_M_AXI_MEM_BUS_USER_VALUE = 0;
parameter    C_M_AXI_MEM_BUS_PROT_VALUE = 0;
parameter    C_M_AXI_MEM_BUS_CACHE_VALUE = 3;
parameter    C_M_AXI_ID_WIDTH = 1;
parameter    C_M_AXI_ADDR_WIDTH = 32;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_AWUSER_WIDTH = 1;
parameter    C_M_AXI_ARUSER_WIDTH = 1;
parameter    C_M_AXI_WUSER_WIDTH = 1;
parameter    C_M_AXI_RUSER_WIDTH = 1;
parameter    C_M_AXI_BUSER_WIDTH = 1;

parameter C_S_AXI_CTRL_BUS_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_MEM_BUS_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   s_axi_ctrl_bus_AWVALID;
output   s_axi_ctrl_bus_AWREADY;
input  [C_S_AXI_CTRL_BUS_ADDR_WIDTH - 1:0] s_axi_ctrl_bus_AWADDR;
input   s_axi_ctrl_bus_WVALID;
output   s_axi_ctrl_bus_WREADY;
input  [C_S_AXI_CTRL_BUS_DATA_WIDTH - 1:0] s_axi_ctrl_bus_WDATA;
input  [C_S_AXI_CTRL_BUS_WSTRB_WIDTH - 1:0] s_axi_ctrl_bus_WSTRB;
input   s_axi_ctrl_bus_ARVALID;
output   s_axi_ctrl_bus_ARREADY;
input  [C_S_AXI_CTRL_BUS_ADDR_WIDTH - 1:0] s_axi_ctrl_bus_ARADDR;
output   s_axi_ctrl_bus_RVALID;
input   s_axi_ctrl_bus_RREADY;
output  [C_S_AXI_CTRL_BUS_DATA_WIDTH - 1:0] s_axi_ctrl_bus_RDATA;
output  [1:0] s_axi_ctrl_bus_RRESP;
output   s_axi_ctrl_bus_BVALID;
input   s_axi_ctrl_bus_BREADY;
output  [1:0] s_axi_ctrl_bus_BRESP;
input   ap_clk;
input   ap_rst_n;
output   interrupt;
output   m_axi_mem_bus_AWVALID;
input   m_axi_mem_bus_AWREADY;
output  [C_M_AXI_MEM_BUS_ADDR_WIDTH - 1:0] m_axi_mem_bus_AWADDR;
output  [C_M_AXI_MEM_BUS_ID_WIDTH - 1:0] m_axi_mem_bus_AWID;
output  [7:0] m_axi_mem_bus_AWLEN;
output  [2:0] m_axi_mem_bus_AWSIZE;
output  [1:0] m_axi_mem_bus_AWBURST;
output  [1:0] m_axi_mem_bus_AWLOCK;
output  [3:0] m_axi_mem_bus_AWCACHE;
output  [2:0] m_axi_mem_bus_AWPROT;
output  [3:0] m_axi_mem_bus_AWQOS;
output  [3:0] m_axi_mem_bus_AWREGION;
output  [C_M_AXI_MEM_BUS_AWUSER_WIDTH - 1:0] m_axi_mem_bus_AWUSER;
output   m_axi_mem_bus_WVALID;
input   m_axi_mem_bus_WREADY;
output  [C_M_AXI_MEM_BUS_DATA_WIDTH - 1:0] m_axi_mem_bus_WDATA;
output  [C_M_AXI_MEM_BUS_WSTRB_WIDTH - 1:0] m_axi_mem_bus_WSTRB;
output   m_axi_mem_bus_WLAST;
output  [C_M_AXI_MEM_BUS_ID_WIDTH - 1:0] m_axi_mem_bus_WID;
output  [C_M_AXI_MEM_BUS_WUSER_WIDTH - 1:0] m_axi_mem_bus_WUSER;
output   m_axi_mem_bus_ARVALID;
input   m_axi_mem_bus_ARREADY;
output  [C_M_AXI_MEM_BUS_ADDR_WIDTH - 1:0] m_axi_mem_bus_ARADDR;
output  [C_M_AXI_MEM_BUS_ID_WIDTH - 1:0] m_axi_mem_bus_ARID;
output  [7:0] m_axi_mem_bus_ARLEN;
output  [2:0] m_axi_mem_bus_ARSIZE;
output  [1:0] m_axi_mem_bus_ARBURST;
output  [1:0] m_axi_mem_bus_ARLOCK;
output  [3:0] m_axi_mem_bus_ARCACHE;
output  [2:0] m_axi_mem_bus_ARPROT;
output  [3:0] m_axi_mem_bus_ARQOS;
output  [3:0] m_axi_mem_bus_ARREGION;
output  [C_M_AXI_MEM_BUS_ARUSER_WIDTH - 1:0] m_axi_mem_bus_ARUSER;
input   m_axi_mem_bus_RVALID;
output   m_axi_mem_bus_RREADY;
input  [C_M_AXI_MEM_BUS_DATA_WIDTH - 1:0] m_axi_mem_bus_RDATA;
input   m_axi_mem_bus_RLAST;
input  [C_M_AXI_MEM_BUS_ID_WIDTH - 1:0] m_axi_mem_bus_RID;
input  [C_M_AXI_MEM_BUS_RUSER_WIDTH - 1:0] m_axi_mem_bus_RUSER;
input  [1:0] m_axi_mem_bus_RRESP;
input   m_axi_mem_bus_BVALID;
output   m_axi_mem_bus_BREADY;
input  [1:0] m_axi_mem_bus_BRESP;
input  [C_M_AXI_MEM_BUS_ID_WIDTH - 1:0] m_axi_mem_bus_BID;
input  [C_M_AXI_MEM_BUS_BUSER_WIDTH - 1:0] m_axi_mem_bus_BUSER;

 reg    ap_rst_n_inv;
wire    ap_start;
wire    ap_ready;
wire    ap_done;
wire    ap_idle;
wire    direction;
wire   [31:0] in_M_real_V;
wire   [31:0] in_M_imag_V;
wire   [31:0] out_M_real_V;
wire   [31:0] out_M_imag_V;
wire    mem_bus_AWREADY;
wire    mem_bus_WREADY;
wire    mem_bus_ARREADY;
wire    mem_bus_RVALID;
wire   [15:0] mem_bus_RDATA;
wire    mem_bus_RLAST;
wire   [0:0] mem_bus_RID;
wire   [0:0] mem_bus_RUSER;
wire   [1:0] mem_bus_RRESP;
wire    mem_bus_BVALID;
wire   [1:0] mem_bus_BRESP;
wire   [0:0] mem_bus_BID;
wire   [0:0] mem_bus_BUSER;
wire    dummy_proc_fe11_U0_ap_start;
wire    dummy_proc_fe11_U0_start_full_n;
wire    dummy_proc_fe11_U0_ap_done;
wire    dummy_proc_fe11_U0_ap_continue;
wire    dummy_proc_fe11_U0_ap_idle;
wire    dummy_proc_fe11_U0_ap_ready;
wire    dummy_proc_fe11_U0_start_out;
wire    dummy_proc_fe11_U0_start_write;
wire   [0:0] dummy_proc_fe11_U0_direction;
wire   [15:0] dummy_proc_fe11_U0_config_data_V_2_din;
wire    dummy_proc_fe11_U0_config_data_V_2_write;
wire   [15:0] dummy_proc_fe11_U0_config_data_V_din;
wire    dummy_proc_fe11_U0_config_data_V_write;
wire    dummy_proc_fe11_U0_m_axi_in_M_real_V_AWVALID;
wire   [31:0] dummy_proc_fe11_U0_m_axi_in_M_real_V_AWADDR;
wire   [0:0] dummy_proc_fe11_U0_m_axi_in_M_real_V_AWID;
wire   [31:0] dummy_proc_fe11_U0_m_axi_in_M_real_V_AWLEN;
wire   [2:0] dummy_proc_fe11_U0_m_axi_in_M_real_V_AWSIZE;
wire   [1:0] dummy_proc_fe11_U0_m_axi_in_M_real_V_AWBURST;
wire   [1:0] dummy_proc_fe11_U0_m_axi_in_M_real_V_AWLOCK;
wire   [3:0] dummy_proc_fe11_U0_m_axi_in_M_real_V_AWCACHE;
wire   [2:0] dummy_proc_fe11_U0_m_axi_in_M_real_V_AWPROT;
wire   [3:0] dummy_proc_fe11_U0_m_axi_in_M_real_V_AWQOS;
wire   [3:0] dummy_proc_fe11_U0_m_axi_in_M_real_V_AWREGION;
wire   [0:0] dummy_proc_fe11_U0_m_axi_in_M_real_V_AWUSER;
wire    dummy_proc_fe11_U0_m_axi_in_M_real_V_WVALID;
wire   [15:0] dummy_proc_fe11_U0_m_axi_in_M_real_V_WDATA;
wire   [1:0] dummy_proc_fe11_U0_m_axi_in_M_real_V_WSTRB;
wire    dummy_proc_fe11_U0_m_axi_in_M_real_V_WLAST;
wire   [0:0] dummy_proc_fe11_U0_m_axi_in_M_real_V_WID;
wire   [0:0] dummy_proc_fe11_U0_m_axi_in_M_real_V_WUSER;
wire    dummy_proc_fe11_U0_m_axi_in_M_real_V_ARVALID;
wire   [31:0] dummy_proc_fe11_U0_m_axi_in_M_real_V_ARADDR;
wire   [0:0] dummy_proc_fe11_U0_m_axi_in_M_real_V_ARID;
wire   [31:0] dummy_proc_fe11_U0_m_axi_in_M_real_V_ARLEN;
wire   [2:0] dummy_proc_fe11_U0_m_axi_in_M_real_V_ARSIZE;
wire   [1:0] dummy_proc_fe11_U0_m_axi_in_M_real_V_ARBURST;
wire   [1:0] dummy_proc_fe11_U0_m_axi_in_M_real_V_ARLOCK;
wire   [3:0] dummy_proc_fe11_U0_m_axi_in_M_real_V_ARCACHE;
wire   [2:0] dummy_proc_fe11_U0_m_axi_in_M_real_V_ARPROT;
wire   [3:0] dummy_proc_fe11_U0_m_axi_in_M_real_V_ARQOS;
wire   [3:0] dummy_proc_fe11_U0_m_axi_in_M_real_V_ARREGION;
wire   [0:0] dummy_proc_fe11_U0_m_axi_in_M_real_V_ARUSER;
wire    dummy_proc_fe11_U0_m_axi_in_M_real_V_RREADY;
wire    dummy_proc_fe11_U0_m_axi_in_M_real_V_BREADY;
wire   [31:0] dummy_proc_fe11_U0_out_r_din;
wire    dummy_proc_fe11_U0_out_r_write;
wire   [31:0] dummy_proc_fe11_U0_out_M_real_V_out_din;
wire    dummy_proc_fe11_U0_out_M_real_V_out_write;
wire   [31:0] dummy_proc_fe11_U0_out_M_imag_V_out_din;
wire    dummy_proc_fe11_U0_out_M_imag_V_out_write;
wire    fft_config1_U0_ap_start;
wire    fft_config1_U0_ap_done;
wire    fft_config1_U0_ap_idle;
wire    fft_config1_U0_ap_ready;
wire    fft_config1_U0_ap_continue;
wire    fft_config1_U0_xn_read;
wire   [31:0] fft_config1_U0_xk_din;
wire    fft_config1_U0_xk_write;
wire   [7:0] fft_config1_U0_status_data_V_din;
wire    fft_config1_U0_status_data_V_write;
wire    fft_config1_U0_config_ch_data_V_read;
wire    dummy_proc_middle_U0_ap_start;
wire    dummy_proc_middle_U0_ap_done;
wire    dummy_proc_middle_U0_ap_continue;
wire    dummy_proc_middle_U0_ap_idle;
wire    dummy_proc_middle_U0_ap_ready;
wire    dummy_proc_middle_U0_start_out;
wire    dummy_proc_middle_U0_start_write;
wire    dummy_proc_middle_U0_config_in_data_V_read;
wire   [15:0] dummy_proc_middle_U0_config_out_data_V_din;
wire    dummy_proc_middle_U0_config_out_data_V_write;
wire    dummy_proc_middle_U0_st_in_data_V_read;
wire    dummy_proc_middle_U0_in_r_read;
wire   [31:0] dummy_proc_middle_U0_out_r_din;
wire    dummy_proc_middle_U0_out_r_write;
wire    fft_config1_1_U0_ap_start;
wire    fft_config1_1_U0_ap_done;
wire    fft_config1_1_U0_ap_idle;
wire    fft_config1_1_U0_ap_ready;
wire    fft_config1_1_U0_ap_continue;
wire    fft_config1_1_U0_xn_read;
wire   [31:0] fft_config1_1_U0_xk_din;
wire    fft_config1_1_U0_xk_write;
wire   [7:0] fft_config1_1_U0_status_data_V_din;
wire    fft_config1_1_U0_status_data_V_write;
wire    fft_config1_1_U0_config_ch_data_V_read;
wire    dummy_proc_be_U0_ap_start;
wire    dummy_proc_be_U0_ap_done;
wire    dummy_proc_be_U0_ap_continue;
wire    dummy_proc_be_U0_ap_idle;
wire    dummy_proc_be_U0_ap_ready;
wire    dummy_proc_be_U0_status_in_data_V_read;
wire    dummy_proc_be_U0_ovflo;
wire    dummy_proc_be_U0_ovflo_ap_vld;
wire    dummy_proc_be_U0_in_r_read;
wire    dummy_proc_be_U0_m_axi_out_M_real_V_AWVALID;
wire   [31:0] dummy_proc_be_U0_m_axi_out_M_real_V_AWADDR;
wire   [0:0] dummy_proc_be_U0_m_axi_out_M_real_V_AWID;
wire   [31:0] dummy_proc_be_U0_m_axi_out_M_real_V_AWLEN;
wire   [2:0] dummy_proc_be_U0_m_axi_out_M_real_V_AWSIZE;
wire   [1:0] dummy_proc_be_U0_m_axi_out_M_real_V_AWBURST;
wire   [1:0] dummy_proc_be_U0_m_axi_out_M_real_V_AWLOCK;
wire   [3:0] dummy_proc_be_U0_m_axi_out_M_real_V_AWCACHE;
wire   [2:0] dummy_proc_be_U0_m_axi_out_M_real_V_AWPROT;
wire   [3:0] dummy_proc_be_U0_m_axi_out_M_real_V_AWQOS;
wire   [3:0] dummy_proc_be_U0_m_axi_out_M_real_V_AWREGION;
wire   [0:0] dummy_proc_be_U0_m_axi_out_M_real_V_AWUSER;
wire    dummy_proc_be_U0_m_axi_out_M_real_V_WVALID;
wire   [15:0] dummy_proc_be_U0_m_axi_out_M_real_V_WDATA;
wire   [1:0] dummy_proc_be_U0_m_axi_out_M_real_V_WSTRB;
wire    dummy_proc_be_U0_m_axi_out_M_real_V_WLAST;
wire   [0:0] dummy_proc_be_U0_m_axi_out_M_real_V_WID;
wire   [0:0] dummy_proc_be_U0_m_axi_out_M_real_V_WUSER;
wire    dummy_proc_be_U0_m_axi_out_M_real_V_ARVALID;
wire   [31:0] dummy_proc_be_U0_m_axi_out_M_real_V_ARADDR;
wire   [0:0] dummy_proc_be_U0_m_axi_out_M_real_V_ARID;
wire   [31:0] dummy_proc_be_U0_m_axi_out_M_real_V_ARLEN;
wire   [2:0] dummy_proc_be_U0_m_axi_out_M_real_V_ARSIZE;
wire   [1:0] dummy_proc_be_U0_m_axi_out_M_real_V_ARBURST;
wire   [1:0] dummy_proc_be_U0_m_axi_out_M_real_V_ARLOCK;
wire   [3:0] dummy_proc_be_U0_m_axi_out_M_real_V_ARCACHE;
wire   [2:0] dummy_proc_be_U0_m_axi_out_M_real_V_ARPROT;
wire   [3:0] dummy_proc_be_U0_m_axi_out_M_real_V_ARQOS;
wire   [3:0] dummy_proc_be_U0_m_axi_out_M_real_V_ARREGION;
wire   [0:0] dummy_proc_be_U0_m_axi_out_M_real_V_ARUSER;
wire    dummy_proc_be_U0_m_axi_out_M_real_V_RREADY;
wire    dummy_proc_be_U0_m_axi_out_M_real_V_BREADY;
wire    dummy_proc_be_U0_out_M_real_V_offset_read;
wire    dummy_proc_be_U0_out_M_imag_V_offset_read;
wire    ap_sync_continue;
wire    fft_config1_data_V_full_n;
wire   [15:0] fft_config1_data_V_dout;
wire    fft_config1_data_V_empty_n;
wire    fft_config1_data_V_c_full_n;
wire   [15:0] fft_config1_data_V_c_dout;
wire    fft_config1_data_V_c_empty_n;
wire    xn1_channel_full_n;
wire   [31:0] xn1_channel_dout;
wire    xn1_channel_empty_n;
wire    out_M_real_V_c_full_n;
wire   [31:0] out_M_real_V_c_dout;
wire    out_M_real_V_c_empty_n;
wire    out_M_imag_V_c_full_n;
wire   [31:0] out_M_imag_V_c_dout;
wire    out_M_imag_V_c_empty_n;
wire    xk1_channel_full_n;
wire   [31:0] xk1_channel_dout;
wire    xk1_channel_empty_n;
wire    fft_status1_data_V_full_n;
wire   [7:0] fft_status1_data_V_dout;
wire    fft_status1_data_V_empty_n;
wire    fft_config2_data_V_full_n;
wire   [15:0] fft_config2_data_V_dout;
wire    fft_config2_data_V_empty_n;
wire    xn2_channel_full_n;
wire   [31:0] xn2_channel_dout;
wire    xn2_channel_empty_n;
wire    xk2_channel_full_n;
wire   [31:0] xk2_channel_dout;
wire    xk2_channel_empty_n;
wire    fft_status2_data_V_full_n;
wire   [7:0] fft_status2_data_V_dout;
wire    fft_status2_data_V_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
wire   [0:0] start_for_fft_config1_U0_din;
wire    start_for_fft_config1_U0_full_n;
wire   [0:0] start_for_fft_config1_U0_dout;
wire    start_for_fft_config1_U0_empty_n;
wire   [0:0] start_for_dummy_proc_middle_U0_din;
wire    start_for_dummy_proc_middle_U0_full_n;
wire   [0:0] start_for_dummy_proc_middle_U0_dout;
wire    start_for_dummy_proc_middle_U0_empty_n;
wire   [0:0] start_for_dummy_proc_be_U0_din;
wire    start_for_dummy_proc_be_U0_full_n;
wire   [0:0] start_for_dummy_proc_be_U0_dout;
wire    start_for_dummy_proc_be_U0_empty_n;
wire    fft_config1_U0_start_full_n;
wire    fft_config1_U0_start_write;
wire   [0:0] start_for_fft_config1_1_U0_din;
wire    start_for_fft_config1_1_U0_full_n;
wire   [0:0] start_for_fft_config1_1_U0_dout;
wire    start_for_fft_config1_1_U0_empty_n;
wire    fft_config1_1_U0_start_full_n;
wire    fft_config1_1_U0_start_write;
wire    dummy_proc_be_U0_start_full_n;
wire    dummy_proc_be_U0_start_write;

fft_top_ctrl_bus_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_BUS_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_BUS_DATA_WIDTH ))
fft_top_ctrl_bus_s_axi_U(
    .AWVALID(s_axi_ctrl_bus_AWVALID),
    .AWREADY(s_axi_ctrl_bus_AWREADY),
    .AWADDR(s_axi_ctrl_bus_AWADDR),
    .WVALID(s_axi_ctrl_bus_WVALID),
    .WREADY(s_axi_ctrl_bus_WREADY),
    .WDATA(s_axi_ctrl_bus_WDATA),
    .WSTRB(s_axi_ctrl_bus_WSTRB),
    .ARVALID(s_axi_ctrl_bus_ARVALID),
    .ARREADY(s_axi_ctrl_bus_ARREADY),
    .ARADDR(s_axi_ctrl_bus_ARADDR),
    .RVALID(s_axi_ctrl_bus_RVALID),
    .RREADY(s_axi_ctrl_bus_RREADY),
    .RDATA(s_axi_ctrl_bus_RDATA),
    .RRESP(s_axi_ctrl_bus_RRESP),
    .BVALID(s_axi_ctrl_bus_BVALID),
    .BREADY(s_axi_ctrl_bus_BREADY),
    .BRESP(s_axi_ctrl_bus_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle),
    .direction(direction),
    .in_M_real_V(in_M_real_V),
    .in_M_imag_V(in_M_imag_V),
    .out_M_real_V(out_M_real_V),
    .out_M_imag_V(out_M_imag_V),
    .ovflo(dummy_proc_be_U0_ovflo),
    .ovflo_ap_vld(dummy_proc_be_U0_ovflo_ap_vld)
);

fft_top_mem_bus_m_axi #(
    .CONSERVATIVE( 0 ),
    .USER_DW( 16 ),
    .USER_AW( 32 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_MEM_BUS_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_MEM_BUS_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_MEM_BUS_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_MEM_BUS_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_MEM_BUS_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_MEM_BUS_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_MEM_BUS_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_MEM_BUS_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_MEM_BUS_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_MEM_BUS_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_MEM_BUS_CACHE_VALUE ))
fft_top_mem_bus_m_axi_U(
    .AWVALID(m_axi_mem_bus_AWVALID),
    .AWREADY(m_axi_mem_bus_AWREADY),
    .AWADDR(m_axi_mem_bus_AWADDR),
    .AWID(m_axi_mem_bus_AWID),
    .AWLEN(m_axi_mem_bus_AWLEN),
    .AWSIZE(m_axi_mem_bus_AWSIZE),
    .AWBURST(m_axi_mem_bus_AWBURST),
    .AWLOCK(m_axi_mem_bus_AWLOCK),
    .AWCACHE(m_axi_mem_bus_AWCACHE),
    .AWPROT(m_axi_mem_bus_AWPROT),
    .AWQOS(m_axi_mem_bus_AWQOS),
    .AWREGION(m_axi_mem_bus_AWREGION),
    .AWUSER(m_axi_mem_bus_AWUSER),
    .WVALID(m_axi_mem_bus_WVALID),
    .WREADY(m_axi_mem_bus_WREADY),
    .WDATA(m_axi_mem_bus_WDATA),
    .WSTRB(m_axi_mem_bus_WSTRB),
    .WLAST(m_axi_mem_bus_WLAST),
    .WID(m_axi_mem_bus_WID),
    .WUSER(m_axi_mem_bus_WUSER),
    .ARVALID(m_axi_mem_bus_ARVALID),
    .ARREADY(m_axi_mem_bus_ARREADY),
    .ARADDR(m_axi_mem_bus_ARADDR),
    .ARID(m_axi_mem_bus_ARID),
    .ARLEN(m_axi_mem_bus_ARLEN),
    .ARSIZE(m_axi_mem_bus_ARSIZE),
    .ARBURST(m_axi_mem_bus_ARBURST),
    .ARLOCK(m_axi_mem_bus_ARLOCK),
    .ARCACHE(m_axi_mem_bus_ARCACHE),
    .ARPROT(m_axi_mem_bus_ARPROT),
    .ARQOS(m_axi_mem_bus_ARQOS),
    .ARREGION(m_axi_mem_bus_ARREGION),
    .ARUSER(m_axi_mem_bus_ARUSER),
    .RVALID(m_axi_mem_bus_RVALID),
    .RREADY(m_axi_mem_bus_RREADY),
    .RDATA(m_axi_mem_bus_RDATA),
    .RLAST(m_axi_mem_bus_RLAST),
    .RID(m_axi_mem_bus_RID),
    .RUSER(m_axi_mem_bus_RUSER),
    .RRESP(m_axi_mem_bus_RRESP),
    .BVALID(m_axi_mem_bus_BVALID),
    .BREADY(m_axi_mem_bus_BREADY),
    .BRESP(m_axi_mem_bus_BRESP),
    .BID(m_axi_mem_bus_BID),
    .BUSER(m_axi_mem_bus_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(dummy_proc_fe11_U0_m_axi_in_M_real_V_ARVALID),
    .I_ARREADY(mem_bus_ARREADY),
    .I_ARADDR(dummy_proc_fe11_U0_m_axi_in_M_real_V_ARADDR),
    .I_ARID(dummy_proc_fe11_U0_m_axi_in_M_real_V_ARID),
    .I_ARLEN(dummy_proc_fe11_U0_m_axi_in_M_real_V_ARLEN),
    .I_ARSIZE(dummy_proc_fe11_U0_m_axi_in_M_real_V_ARSIZE),
    .I_ARLOCK(dummy_proc_fe11_U0_m_axi_in_M_real_V_ARLOCK),
    .I_ARCACHE(dummy_proc_fe11_U0_m_axi_in_M_real_V_ARCACHE),
    .I_ARQOS(dummy_proc_fe11_U0_m_axi_in_M_real_V_ARQOS),
    .I_ARPROT(dummy_proc_fe11_U0_m_axi_in_M_real_V_ARPROT),
    .I_ARUSER(dummy_proc_fe11_U0_m_axi_in_M_real_V_ARUSER),
    .I_ARBURST(dummy_proc_fe11_U0_m_axi_in_M_real_V_ARBURST),
    .I_ARREGION(dummy_proc_fe11_U0_m_axi_in_M_real_V_ARREGION),
    .I_RVALID(mem_bus_RVALID),
    .I_RREADY(dummy_proc_fe11_U0_m_axi_in_M_real_V_RREADY),
    .I_RDATA(mem_bus_RDATA),
    .I_RID(mem_bus_RID),
    .I_RUSER(mem_bus_RUSER),
    .I_RRESP(mem_bus_RRESP),
    .I_RLAST(mem_bus_RLAST),
    .I_AWVALID(dummy_proc_be_U0_m_axi_out_M_real_V_AWVALID),
    .I_AWREADY(mem_bus_AWREADY),
    .I_AWADDR(dummy_proc_be_U0_m_axi_out_M_real_V_AWADDR),
    .I_AWID(dummy_proc_be_U0_m_axi_out_M_real_V_AWID),
    .I_AWLEN(dummy_proc_be_U0_m_axi_out_M_real_V_AWLEN),
    .I_AWSIZE(dummy_proc_be_U0_m_axi_out_M_real_V_AWSIZE),
    .I_AWLOCK(dummy_proc_be_U0_m_axi_out_M_real_V_AWLOCK),
    .I_AWCACHE(dummy_proc_be_U0_m_axi_out_M_real_V_AWCACHE),
    .I_AWQOS(dummy_proc_be_U0_m_axi_out_M_real_V_AWQOS),
    .I_AWPROT(dummy_proc_be_U0_m_axi_out_M_real_V_AWPROT),
    .I_AWUSER(dummy_proc_be_U0_m_axi_out_M_real_V_AWUSER),
    .I_AWBURST(dummy_proc_be_U0_m_axi_out_M_real_V_AWBURST),
    .I_AWREGION(dummy_proc_be_U0_m_axi_out_M_real_V_AWREGION),
    .I_WVALID(dummy_proc_be_U0_m_axi_out_M_real_V_WVALID),
    .I_WREADY(mem_bus_WREADY),
    .I_WDATA(dummy_proc_be_U0_m_axi_out_M_real_V_WDATA),
    .I_WID(dummy_proc_be_U0_m_axi_out_M_real_V_WID),
    .I_WUSER(dummy_proc_be_U0_m_axi_out_M_real_V_WUSER),
    .I_WLAST(dummy_proc_be_U0_m_axi_out_M_real_V_WLAST),
    .I_WSTRB(dummy_proc_be_U0_m_axi_out_M_real_V_WSTRB),
    .I_BVALID(mem_bus_BVALID),
    .I_BREADY(dummy_proc_be_U0_m_axi_out_M_real_V_BREADY),
    .I_BRESP(mem_bus_BRESP),
    .I_BID(mem_bus_BID),
    .I_BUSER(mem_bus_BUSER)
);

dummy_proc_fe11 dummy_proc_fe11_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(dummy_proc_fe11_U0_ap_start),
    .start_full_n(dummy_proc_fe11_U0_start_full_n),
    .ap_done(dummy_proc_fe11_U0_ap_done),
    .ap_continue(dummy_proc_fe11_U0_ap_continue),
    .ap_idle(dummy_proc_fe11_U0_ap_idle),
    .ap_ready(dummy_proc_fe11_U0_ap_ready),
    .start_out(dummy_proc_fe11_U0_start_out),
    .start_write(dummy_proc_fe11_U0_start_write),
    .direction(dummy_proc_fe11_U0_direction),
    .config_data_V_2_din(dummy_proc_fe11_U0_config_data_V_2_din),
    .config_data_V_2_full_n(fft_config1_data_V_full_n),
    .config_data_V_2_write(dummy_proc_fe11_U0_config_data_V_2_write),
    .config_data_V_din(dummy_proc_fe11_U0_config_data_V_din),
    .config_data_V_full_n(fft_config1_data_V_c_full_n),
    .config_data_V_write(dummy_proc_fe11_U0_config_data_V_write),
    .m_axi_in_M_real_V_AWVALID(dummy_proc_fe11_U0_m_axi_in_M_real_V_AWVALID),
    .m_axi_in_M_real_V_AWREADY(1'b0),
    .m_axi_in_M_real_V_AWADDR(dummy_proc_fe11_U0_m_axi_in_M_real_V_AWADDR),
    .m_axi_in_M_real_V_AWID(dummy_proc_fe11_U0_m_axi_in_M_real_V_AWID),
    .m_axi_in_M_real_V_AWLEN(dummy_proc_fe11_U0_m_axi_in_M_real_V_AWLEN),
    .m_axi_in_M_real_V_AWSIZE(dummy_proc_fe11_U0_m_axi_in_M_real_V_AWSIZE),
    .m_axi_in_M_real_V_AWBURST(dummy_proc_fe11_U0_m_axi_in_M_real_V_AWBURST),
    .m_axi_in_M_real_V_AWLOCK(dummy_proc_fe11_U0_m_axi_in_M_real_V_AWLOCK),
    .m_axi_in_M_real_V_AWCACHE(dummy_proc_fe11_U0_m_axi_in_M_real_V_AWCACHE),
    .m_axi_in_M_real_V_AWPROT(dummy_proc_fe11_U0_m_axi_in_M_real_V_AWPROT),
    .m_axi_in_M_real_V_AWQOS(dummy_proc_fe11_U0_m_axi_in_M_real_V_AWQOS),
    .m_axi_in_M_real_V_AWREGION(dummy_proc_fe11_U0_m_axi_in_M_real_V_AWREGION),
    .m_axi_in_M_real_V_AWUSER(dummy_proc_fe11_U0_m_axi_in_M_real_V_AWUSER),
    .m_axi_in_M_real_V_WVALID(dummy_proc_fe11_U0_m_axi_in_M_real_V_WVALID),
    .m_axi_in_M_real_V_WREADY(1'b0),
    .m_axi_in_M_real_V_WDATA(dummy_proc_fe11_U0_m_axi_in_M_real_V_WDATA),
    .m_axi_in_M_real_V_WSTRB(dummy_proc_fe11_U0_m_axi_in_M_real_V_WSTRB),
    .m_axi_in_M_real_V_WLAST(dummy_proc_fe11_U0_m_axi_in_M_real_V_WLAST),
    .m_axi_in_M_real_V_WID(dummy_proc_fe11_U0_m_axi_in_M_real_V_WID),
    .m_axi_in_M_real_V_WUSER(dummy_proc_fe11_U0_m_axi_in_M_real_V_WUSER),
    .m_axi_in_M_real_V_ARVALID(dummy_proc_fe11_U0_m_axi_in_M_real_V_ARVALID),
    .m_axi_in_M_real_V_ARREADY(mem_bus_ARREADY),
    .m_axi_in_M_real_V_ARADDR(dummy_proc_fe11_U0_m_axi_in_M_real_V_ARADDR),
    .m_axi_in_M_real_V_ARID(dummy_proc_fe11_U0_m_axi_in_M_real_V_ARID),
    .m_axi_in_M_real_V_ARLEN(dummy_proc_fe11_U0_m_axi_in_M_real_V_ARLEN),
    .m_axi_in_M_real_V_ARSIZE(dummy_proc_fe11_U0_m_axi_in_M_real_V_ARSIZE),
    .m_axi_in_M_real_V_ARBURST(dummy_proc_fe11_U0_m_axi_in_M_real_V_ARBURST),
    .m_axi_in_M_real_V_ARLOCK(dummy_proc_fe11_U0_m_axi_in_M_real_V_ARLOCK),
    .m_axi_in_M_real_V_ARCACHE(dummy_proc_fe11_U0_m_axi_in_M_real_V_ARCACHE),
    .m_axi_in_M_real_V_ARPROT(dummy_proc_fe11_U0_m_axi_in_M_real_V_ARPROT),
    .m_axi_in_M_real_V_ARQOS(dummy_proc_fe11_U0_m_axi_in_M_real_V_ARQOS),
    .m_axi_in_M_real_V_ARREGION(dummy_proc_fe11_U0_m_axi_in_M_real_V_ARREGION),
    .m_axi_in_M_real_V_ARUSER(dummy_proc_fe11_U0_m_axi_in_M_real_V_ARUSER),
    .m_axi_in_M_real_V_RVALID(mem_bus_RVALID),
    .m_axi_in_M_real_V_RREADY(dummy_proc_fe11_U0_m_axi_in_M_real_V_RREADY),
    .m_axi_in_M_real_V_RDATA(mem_bus_RDATA),
    .m_axi_in_M_real_V_RLAST(mem_bus_RLAST),
    .m_axi_in_M_real_V_RID(mem_bus_RID),
    .m_axi_in_M_real_V_RUSER(mem_bus_RUSER),
    .m_axi_in_M_real_V_RRESP(mem_bus_RRESP),
    .m_axi_in_M_real_V_BVALID(1'b0),
    .m_axi_in_M_real_V_BREADY(dummy_proc_fe11_U0_m_axi_in_M_real_V_BREADY),
    .m_axi_in_M_real_V_BRESP(2'd0),
    .m_axi_in_M_real_V_BID(1'd0),
    .m_axi_in_M_real_V_BUSER(1'd0),
    .in_M_real_V_offset(in_M_real_V),
    .in_M_imag_V_offset(in_M_imag_V),
    .out_r_din(dummy_proc_fe11_U0_out_r_din),
    .out_r_full_n(xn1_channel_full_n),
    .out_r_write(dummy_proc_fe11_U0_out_r_write),
    .out_M_real_V(out_M_real_V),
    .out_M_imag_V(out_M_imag_V),
    .out_M_real_V_out_din(dummy_proc_fe11_U0_out_M_real_V_out_din),
    .out_M_real_V_out_full_n(out_M_real_V_c_full_n),
    .out_M_real_V_out_write(dummy_proc_fe11_U0_out_M_real_V_out_write),
    .out_M_imag_V_out_din(dummy_proc_fe11_U0_out_M_imag_V_out_din),
    .out_M_imag_V_out_full_n(out_M_imag_V_c_full_n),
    .out_M_imag_V_out_write(dummy_proc_fe11_U0_out_M_imag_V_out_write)
);

fft_config1_s fft_config1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(fft_config1_U0_ap_start),
    .ap_ce(1'b1),
    .ap_done(fft_config1_U0_ap_done),
    .ap_idle(fft_config1_U0_ap_idle),
    .ap_ready(fft_config1_U0_ap_ready),
    .ap_continue(fft_config1_U0_ap_continue),
    .xn_dout(xn1_channel_dout),
    .xn_empty_n(xn1_channel_empty_n),
    .xn_read(fft_config1_U0_xn_read),
    .xk_din(fft_config1_U0_xk_din),
    .xk_full_n(xk1_channel_full_n),
    .xk_write(fft_config1_U0_xk_write),
    .status_data_V_din(fft_config1_U0_status_data_V_din),
    .status_data_V_full_n(fft_status1_data_V_full_n),
    .status_data_V_write(fft_config1_U0_status_data_V_write),
    .config_ch_data_V_dout(fft_config1_data_V_dout),
    .config_ch_data_V_empty_n(fft_config1_data_V_empty_n),
    .config_ch_data_V_read(fft_config1_U0_config_ch_data_V_read)
);

dummy_proc_middle dummy_proc_middle_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(dummy_proc_middle_U0_ap_start),
    .start_full_n(start_for_fft_config1_1_U0_full_n),
    .ap_done(dummy_proc_middle_U0_ap_done),
    .ap_continue(dummy_proc_middle_U0_ap_continue),
    .ap_idle(dummy_proc_middle_U0_ap_idle),
    .ap_ready(dummy_proc_middle_U0_ap_ready),
    .start_out(dummy_proc_middle_U0_start_out),
    .start_write(dummy_proc_middle_U0_start_write),
    .config_in_data_V_dout(fft_config1_data_V_c_dout),
    .config_in_data_V_empty_n(fft_config1_data_V_c_empty_n),
    .config_in_data_V_read(dummy_proc_middle_U0_config_in_data_V_read),
    .config_out_data_V_din(dummy_proc_middle_U0_config_out_data_V_din),
    .config_out_data_V_full_n(fft_config2_data_V_full_n),
    .config_out_data_V_write(dummy_proc_middle_U0_config_out_data_V_write),
    .st_in_data_V_dout(fft_status1_data_V_dout),
    .st_in_data_V_empty_n(fft_status1_data_V_empty_n),
    .st_in_data_V_read(dummy_proc_middle_U0_st_in_data_V_read),
    .in_r_dout(xk1_channel_dout),
    .in_r_empty_n(xk1_channel_empty_n),
    .in_r_read(dummy_proc_middle_U0_in_r_read),
    .out_r_din(dummy_proc_middle_U0_out_r_din),
    .out_r_full_n(xn2_channel_full_n),
    .out_r_write(dummy_proc_middle_U0_out_r_write)
);

fft_config1_1 fft_config1_1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(fft_config1_1_U0_ap_start),
    .ap_ce(1'b1),
    .ap_done(fft_config1_1_U0_ap_done),
    .ap_idle(fft_config1_1_U0_ap_idle),
    .ap_ready(fft_config1_1_U0_ap_ready),
    .ap_continue(fft_config1_1_U0_ap_continue),
    .xn_dout(xn2_channel_dout),
    .xn_empty_n(xn2_channel_empty_n),
    .xn_read(fft_config1_1_U0_xn_read),
    .xk_din(fft_config1_1_U0_xk_din),
    .xk_full_n(xk2_channel_full_n),
    .xk_write(fft_config1_1_U0_xk_write),
    .status_data_V_din(fft_config1_1_U0_status_data_V_din),
    .status_data_V_full_n(fft_status2_data_V_full_n),
    .status_data_V_write(fft_config1_1_U0_status_data_V_write),
    .config_ch_data_V_dout(fft_config2_data_V_dout),
    .config_ch_data_V_empty_n(fft_config2_data_V_empty_n),
    .config_ch_data_V_read(fft_config1_1_U0_config_ch_data_V_read)
);

dummy_proc_be dummy_proc_be_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(dummy_proc_be_U0_ap_start),
    .ap_done(dummy_proc_be_U0_ap_done),
    .ap_continue(dummy_proc_be_U0_ap_continue),
    .ap_idle(dummy_proc_be_U0_ap_idle),
    .ap_ready(dummy_proc_be_U0_ap_ready),
    .status_in_data_V_dout(fft_status2_data_V_dout),
    .status_in_data_V_empty_n(fft_status2_data_V_empty_n),
    .status_in_data_V_read(dummy_proc_be_U0_status_in_data_V_read),
    .ovflo(dummy_proc_be_U0_ovflo),
    .ovflo_ap_vld(dummy_proc_be_U0_ovflo_ap_vld),
    .in_r_dout(xk2_channel_dout),
    .in_r_empty_n(xk2_channel_empty_n),
    .in_r_read(dummy_proc_be_U0_in_r_read),
    .m_axi_out_M_real_V_AWVALID(dummy_proc_be_U0_m_axi_out_M_real_V_AWVALID),
    .m_axi_out_M_real_V_AWREADY(mem_bus_AWREADY),
    .m_axi_out_M_real_V_AWADDR(dummy_proc_be_U0_m_axi_out_M_real_V_AWADDR),
    .m_axi_out_M_real_V_AWID(dummy_proc_be_U0_m_axi_out_M_real_V_AWID),
    .m_axi_out_M_real_V_AWLEN(dummy_proc_be_U0_m_axi_out_M_real_V_AWLEN),
    .m_axi_out_M_real_V_AWSIZE(dummy_proc_be_U0_m_axi_out_M_real_V_AWSIZE),
    .m_axi_out_M_real_V_AWBURST(dummy_proc_be_U0_m_axi_out_M_real_V_AWBURST),
    .m_axi_out_M_real_V_AWLOCK(dummy_proc_be_U0_m_axi_out_M_real_V_AWLOCK),
    .m_axi_out_M_real_V_AWCACHE(dummy_proc_be_U0_m_axi_out_M_real_V_AWCACHE),
    .m_axi_out_M_real_V_AWPROT(dummy_proc_be_U0_m_axi_out_M_real_V_AWPROT),
    .m_axi_out_M_real_V_AWQOS(dummy_proc_be_U0_m_axi_out_M_real_V_AWQOS),
    .m_axi_out_M_real_V_AWREGION(dummy_proc_be_U0_m_axi_out_M_real_V_AWREGION),
    .m_axi_out_M_real_V_AWUSER(dummy_proc_be_U0_m_axi_out_M_real_V_AWUSER),
    .m_axi_out_M_real_V_WVALID(dummy_proc_be_U0_m_axi_out_M_real_V_WVALID),
    .m_axi_out_M_real_V_WREADY(mem_bus_WREADY),
    .m_axi_out_M_real_V_WDATA(dummy_proc_be_U0_m_axi_out_M_real_V_WDATA),
    .m_axi_out_M_real_V_WSTRB(dummy_proc_be_U0_m_axi_out_M_real_V_WSTRB),
    .m_axi_out_M_real_V_WLAST(dummy_proc_be_U0_m_axi_out_M_real_V_WLAST),
    .m_axi_out_M_real_V_WID(dummy_proc_be_U0_m_axi_out_M_real_V_WID),
    .m_axi_out_M_real_V_WUSER(dummy_proc_be_U0_m_axi_out_M_real_V_WUSER),
    .m_axi_out_M_real_V_ARVALID(dummy_proc_be_U0_m_axi_out_M_real_V_ARVALID),
    .m_axi_out_M_real_V_ARREADY(1'b0),
    .m_axi_out_M_real_V_ARADDR(dummy_proc_be_U0_m_axi_out_M_real_V_ARADDR),
    .m_axi_out_M_real_V_ARID(dummy_proc_be_U0_m_axi_out_M_real_V_ARID),
    .m_axi_out_M_real_V_ARLEN(dummy_proc_be_U0_m_axi_out_M_real_V_ARLEN),
    .m_axi_out_M_real_V_ARSIZE(dummy_proc_be_U0_m_axi_out_M_real_V_ARSIZE),
    .m_axi_out_M_real_V_ARBURST(dummy_proc_be_U0_m_axi_out_M_real_V_ARBURST),
    .m_axi_out_M_real_V_ARLOCK(dummy_proc_be_U0_m_axi_out_M_real_V_ARLOCK),
    .m_axi_out_M_real_V_ARCACHE(dummy_proc_be_U0_m_axi_out_M_real_V_ARCACHE),
    .m_axi_out_M_real_V_ARPROT(dummy_proc_be_U0_m_axi_out_M_real_V_ARPROT),
    .m_axi_out_M_real_V_ARQOS(dummy_proc_be_U0_m_axi_out_M_real_V_ARQOS),
    .m_axi_out_M_real_V_ARREGION(dummy_proc_be_U0_m_axi_out_M_real_V_ARREGION),
    .m_axi_out_M_real_V_ARUSER(dummy_proc_be_U0_m_axi_out_M_real_V_ARUSER),
    .m_axi_out_M_real_V_RVALID(1'b0),
    .m_axi_out_M_real_V_RREADY(dummy_proc_be_U0_m_axi_out_M_real_V_RREADY),
    .m_axi_out_M_real_V_RDATA(16'd0),
    .m_axi_out_M_real_V_RLAST(1'b0),
    .m_axi_out_M_real_V_RID(1'd0),
    .m_axi_out_M_real_V_RUSER(1'd0),
    .m_axi_out_M_real_V_RRESP(2'd0),
    .m_axi_out_M_real_V_BVALID(mem_bus_BVALID),
    .m_axi_out_M_real_V_BREADY(dummy_proc_be_U0_m_axi_out_M_real_V_BREADY),
    .m_axi_out_M_real_V_BRESP(mem_bus_BRESP),
    .m_axi_out_M_real_V_BID(mem_bus_BID),
    .m_axi_out_M_real_V_BUSER(mem_bus_BUSER),
    .out_M_real_V_offset_dout(out_M_real_V_c_dout),
    .out_M_real_V_offset_empty_n(out_M_real_V_c_empty_n),
    .out_M_real_V_offset_read(dummy_proc_be_U0_out_M_real_V_offset_read),
    .out_M_imag_V_offset_dout(out_M_imag_V_c_dout),
    .out_M_imag_V_offset_empty_n(out_M_imag_V_c_empty_n),
    .out_M_imag_V_offset_read(dummy_proc_be_U0_out_M_imag_V_offset_read)
);

fifo_w16_d2_A fft_config1_data_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dummy_proc_fe11_U0_config_data_V_2_din),
    .if_full_n(fft_config1_data_V_full_n),
    .if_write(dummy_proc_fe11_U0_config_data_V_2_write),
    .if_dout(fft_config1_data_V_dout),
    .if_empty_n(fft_config1_data_V_empty_n),
    .if_read(fft_config1_U0_config_ch_data_V_read)
);

fifo_w16_d2_A fft_config1_data_V_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dummy_proc_fe11_U0_config_data_V_din),
    .if_full_n(fft_config1_data_V_c_full_n),
    .if_write(dummy_proc_fe11_U0_config_data_V_write),
    .if_dout(fft_config1_data_V_c_dout),
    .if_empty_n(fft_config1_data_V_c_empty_n),
    .if_read(dummy_proc_middle_U0_config_in_data_V_read)
);

fifo_w32_d1024_A xn1_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dummy_proc_fe11_U0_out_r_din),
    .if_full_n(xn1_channel_full_n),
    .if_write(dummy_proc_fe11_U0_out_r_write),
    .if_dout(xn1_channel_dout),
    .if_empty_n(xn1_channel_empty_n),
    .if_read(fft_config1_U0_xn_read)
);

fifo_w32_d5_A out_M_real_V_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dummy_proc_fe11_U0_out_M_real_V_out_din),
    .if_full_n(out_M_real_V_c_full_n),
    .if_write(dummy_proc_fe11_U0_out_M_real_V_out_write),
    .if_dout(out_M_real_V_c_dout),
    .if_empty_n(out_M_real_V_c_empty_n),
    .if_read(dummy_proc_be_U0_out_M_real_V_offset_read)
);

fifo_w32_d5_A out_M_imag_V_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dummy_proc_fe11_U0_out_M_imag_V_out_din),
    .if_full_n(out_M_imag_V_c_full_n),
    .if_write(dummy_proc_fe11_U0_out_M_imag_V_out_write),
    .if_dout(out_M_imag_V_c_dout),
    .if_empty_n(out_M_imag_V_c_empty_n),
    .if_read(dummy_proc_be_U0_out_M_imag_V_offset_read)
);

fifo_w32_d1024_A xk1_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fft_config1_U0_xk_din),
    .if_full_n(xk1_channel_full_n),
    .if_write(fft_config1_U0_xk_write),
    .if_dout(xk1_channel_dout),
    .if_empty_n(xk1_channel_empty_n),
    .if_read(dummy_proc_middle_U0_in_r_read)
);

fifo_w8_d2_A fft_status1_data_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fft_config1_U0_status_data_V_din),
    .if_full_n(fft_status1_data_V_full_n),
    .if_write(fft_config1_U0_status_data_V_write),
    .if_dout(fft_status1_data_V_dout),
    .if_empty_n(fft_status1_data_V_empty_n),
    .if_read(dummy_proc_middle_U0_st_in_data_V_read)
);

fifo_w16_d2_A fft_config2_data_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dummy_proc_middle_U0_config_out_data_V_din),
    .if_full_n(fft_config2_data_V_full_n),
    .if_write(dummy_proc_middle_U0_config_out_data_V_write),
    .if_dout(fft_config2_data_V_dout),
    .if_empty_n(fft_config2_data_V_empty_n),
    .if_read(fft_config1_1_U0_config_ch_data_V_read)
);

fifo_w32_d1024_A xn2_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dummy_proc_middle_U0_out_r_din),
    .if_full_n(xn2_channel_full_n),
    .if_write(dummy_proc_middle_U0_out_r_write),
    .if_dout(xn2_channel_dout),
    .if_empty_n(xn2_channel_empty_n),
    .if_read(fft_config1_1_U0_xn_read)
);

fifo_w32_d1024_A xk2_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fft_config1_1_U0_xk_din),
    .if_full_n(xk2_channel_full_n),
    .if_write(fft_config1_1_U0_xk_write),
    .if_dout(xk2_channel_dout),
    .if_empty_n(xk2_channel_empty_n),
    .if_read(dummy_proc_be_U0_in_r_read)
);

fifo_w8_d2_A fft_status2_data_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fft_config1_1_U0_status_data_V_din),
    .if_full_n(fft_status2_data_V_full_n),
    .if_write(fft_config1_1_U0_status_data_V_write),
    .if_dout(fft_status2_data_V_dout),
    .if_empty_n(fft_status2_data_V_empty_n),
    .if_read(dummy_proc_be_U0_status_in_data_V_read)
);

start_for_fft_config1_U0 start_for_fft_config1_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_fft_config1_U0_din),
    .if_full_n(start_for_fft_config1_U0_full_n),
    .if_write(dummy_proc_fe11_U0_start_write),
    .if_dout(start_for_fft_config1_U0_dout),
    .if_empty_n(start_for_fft_config1_U0_empty_n),
    .if_read(fft_config1_U0_ap_ready)
);

start_for_dummy_proc_middle_U0 start_for_dummy_proc_middle_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_dummy_proc_middle_U0_din),
    .if_full_n(start_for_dummy_proc_middle_U0_full_n),
    .if_write(dummy_proc_fe11_U0_start_write),
    .if_dout(start_for_dummy_proc_middle_U0_dout),
    .if_empty_n(start_for_dummy_proc_middle_U0_empty_n),
    .if_read(dummy_proc_middle_U0_ap_ready)
);

start_for_dummy_proc_be_U0 start_for_dummy_proc_be_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_dummy_proc_be_U0_din),
    .if_full_n(start_for_dummy_proc_be_U0_full_n),
    .if_write(dummy_proc_fe11_U0_start_write),
    .if_dout(start_for_dummy_proc_be_U0_dout),
    .if_empty_n(start_for_dummy_proc_be_U0_empty_n),
    .if_read(dummy_proc_be_U0_ap_ready)
);

start_for_fft_config1_1_U0 start_for_fft_config1_1_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_fft_config1_1_U0_din),
    .if_full_n(start_for_fft_config1_1_U0_full_n),
    .if_write(dummy_proc_middle_U0_start_write),
    .if_dout(start_for_fft_config1_1_U0_dout),
    .if_empty_n(start_for_fft_config1_1_U0_empty_n),
    .if_read(fft_config1_1_U0_ap_ready)
);

assign ap_done = dummy_proc_be_U0_ap_done;

assign ap_idle = (fft_config1_U0_ap_idle & fft_config1_1_U0_ap_idle & dummy_proc_middle_U0_ap_idle & dummy_proc_fe11_U0_ap_idle & dummy_proc_be_U0_ap_idle);

assign ap_ready = dummy_proc_fe11_U0_ap_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_continue = 1'b1;

assign ap_sync_done = dummy_proc_be_U0_ap_done;

assign ap_sync_ready = dummy_proc_fe11_U0_ap_ready;

assign dummy_proc_be_U0_ap_continue = 1'b1;

assign dummy_proc_be_U0_ap_start = start_for_dummy_proc_be_U0_empty_n;

assign dummy_proc_be_U0_start_full_n = 1'b1;

assign dummy_proc_be_U0_start_write = 1'b0;

assign dummy_proc_fe11_U0_ap_continue = 1'b1;

assign dummy_proc_fe11_U0_ap_start = ap_start;

assign dummy_proc_fe11_U0_direction = direction;

assign dummy_proc_fe11_U0_start_full_n = (start_for_fft_config1_U0_full_n & start_for_dummy_proc_middle_U0_full_n & start_for_dummy_proc_be_U0_full_n);

assign dummy_proc_middle_U0_ap_continue = 1'b1;

assign dummy_proc_middle_U0_ap_start = start_for_dummy_proc_middle_U0_empty_n;

assign fft_config1_1_U0_ap_continue = 1'b1;

assign fft_config1_1_U0_ap_start = start_for_fft_config1_1_U0_empty_n;

assign fft_config1_1_U0_start_full_n = 1'b1;

assign fft_config1_1_U0_start_write = 1'b0;

assign fft_config1_U0_ap_continue = 1'b1;

assign fft_config1_U0_ap_start = start_for_fft_config1_U0_empty_n;

assign fft_config1_U0_start_full_n = 1'b1;

assign fft_config1_U0_start_write = 1'b0;

assign start_for_dummy_proc_be_U0_din = 1'b1;

assign start_for_dummy_proc_middle_U0_din = 1'b1;

assign start_for_fft_config1_1_U0_din = 1'b1;

assign start_for_fft_config1_U0_din = 1'b1;

endmodule //fft_top
