flora:   
    - partition: 
        - ip_name: "ip1"
          top_name: "ip1_top"
          buffers: [4096, 2048, 1024]
        - ip_name: "ip2"
          top_name: "ip1_top"
          buffers: [4096, 1024]
      use_ila: True
        data_depth: 2048
    - partition: 
        - ip_name: "ip3"
          top_name: "ip3_top" 
          buffers: [1024, 1024]
static_top_module: static_top
static_dcp_file: ./dcp/static.dcp