-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.3
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fft_top is
generic (
    C_S_AXI_CTRL_BUS_ADDR_WIDTH : INTEGER := 7;
    C_S_AXI_CTRL_BUS_DATA_WIDTH : INTEGER := 32;
    C_M_AXI_MEM_BUS_ADDR_WIDTH : INTEGER := 32;
    C_M_AXI_MEM_BUS_ID_WIDTH : INTEGER := 1;
    C_M_AXI_MEM_BUS_AWUSER_WIDTH : INTEGER := 1;
    C_M_AXI_MEM_BUS_DATA_WIDTH : INTEGER := 32;
    C_M_AXI_MEM_BUS_WUSER_WIDTH : INTEGER := 1;
    C_M_AXI_MEM_BUS_ARUSER_WIDTH : INTEGER := 1;
    C_M_AXI_MEM_BUS_RUSER_WIDTH : INTEGER := 1;
    C_M_AXI_MEM_BUS_BUSER_WIDTH : INTEGER := 1;
    C_M_AXI_MEM_BUS_USER_VALUE : INTEGER := 0;
    C_M_AXI_MEM_BUS_PROT_VALUE : INTEGER := 0;
    C_M_AXI_MEM_BUS_CACHE_VALUE : INTEGER := 3 );
port (
    s_axi_ctrl_bus_AWVALID : IN STD_LOGIC;
    s_axi_ctrl_bus_AWREADY : OUT STD_LOGIC;
    s_axi_ctrl_bus_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_BUS_ADDR_WIDTH-1 downto 0);
    s_axi_ctrl_bus_WVALID : IN STD_LOGIC;
    s_axi_ctrl_bus_WREADY : OUT STD_LOGIC;
    s_axi_ctrl_bus_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_BUS_DATA_WIDTH-1 downto 0);
    s_axi_ctrl_bus_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_BUS_DATA_WIDTH/8-1 downto 0);
    s_axi_ctrl_bus_ARVALID : IN STD_LOGIC;
    s_axi_ctrl_bus_ARREADY : OUT STD_LOGIC;
    s_axi_ctrl_bus_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_BUS_ADDR_WIDTH-1 downto 0);
    s_axi_ctrl_bus_RVALID : OUT STD_LOGIC;
    s_axi_ctrl_bus_RREADY : IN STD_LOGIC;
    s_axi_ctrl_bus_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CTRL_BUS_DATA_WIDTH-1 downto 0);
    s_axi_ctrl_bus_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_ctrl_bus_BVALID : OUT STD_LOGIC;
    s_axi_ctrl_bus_BREADY : IN STD_LOGIC;
    s_axi_ctrl_bus_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    interrupt : OUT STD_LOGIC;
    m_axi_mem_bus_AWVALID : OUT STD_LOGIC;
    m_axi_mem_bus_AWREADY : IN STD_LOGIC;
    m_axi_mem_bus_AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_MEM_BUS_ADDR_WIDTH-1 downto 0);
    m_axi_mem_bus_AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_MEM_BUS_ID_WIDTH-1 downto 0);
    m_axi_mem_bus_AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_mem_bus_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_mem_bus_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_mem_bus_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_mem_bus_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_mem_bus_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_mem_bus_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_mem_bus_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_mem_bus_AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_MEM_BUS_AWUSER_WIDTH-1 downto 0);
    m_axi_mem_bus_WVALID : OUT STD_LOGIC;
    m_axi_mem_bus_WREADY : IN STD_LOGIC;
    m_axi_mem_bus_WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_MEM_BUS_DATA_WIDTH-1 downto 0);
    m_axi_mem_bus_WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_MEM_BUS_DATA_WIDTH/8-1 downto 0);
    m_axi_mem_bus_WLAST : OUT STD_LOGIC;
    m_axi_mem_bus_WID : OUT STD_LOGIC_VECTOR (C_M_AXI_MEM_BUS_ID_WIDTH-1 downto 0);
    m_axi_mem_bus_WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_MEM_BUS_WUSER_WIDTH-1 downto 0);
    m_axi_mem_bus_ARVALID : OUT STD_LOGIC;
    m_axi_mem_bus_ARREADY : IN STD_LOGIC;
    m_axi_mem_bus_ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_MEM_BUS_ADDR_WIDTH-1 downto 0);
    m_axi_mem_bus_ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_MEM_BUS_ID_WIDTH-1 downto 0);
    m_axi_mem_bus_ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_mem_bus_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_mem_bus_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_mem_bus_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_mem_bus_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_mem_bus_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_mem_bus_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_mem_bus_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_mem_bus_ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_MEM_BUS_ARUSER_WIDTH-1 downto 0);
    m_axi_mem_bus_RVALID : IN STD_LOGIC;
    m_axi_mem_bus_RREADY : OUT STD_LOGIC;
    m_axi_mem_bus_RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_MEM_BUS_DATA_WIDTH-1 downto 0);
    m_axi_mem_bus_RLAST : IN STD_LOGIC;
    m_axi_mem_bus_RID : IN STD_LOGIC_VECTOR (C_M_AXI_MEM_BUS_ID_WIDTH-1 downto 0);
    m_axi_mem_bus_RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_MEM_BUS_RUSER_WIDTH-1 downto 0);
    m_axi_mem_bus_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_mem_bus_BVALID : IN STD_LOGIC;
    m_axi_mem_bus_BREADY : OUT STD_LOGIC;
    m_axi_mem_bus_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_mem_bus_BID : IN STD_LOGIC_VECTOR (C_M_AXI_MEM_BUS_ID_WIDTH-1 downto 0);
    m_axi_mem_bus_BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_MEM_BUS_BUSER_WIDTH-1 downto 0) );
end;


architecture behav of fft_top is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "fft_top,hls_ip_2018_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7k160tfbg484-1,HLS_INPUT_CLOCK=3.300000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=2.887500,HLS_SYN_LAT=11265,HLS_SYN_TPT=11266,HLS_SYN_MEM=16,HLS_SYN_DSP=24,HLS_SYN_FF=21363,HLS_SYN_LUT=18172,HLS_VERSION=2018_3}";
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant C_S_AXI_WSTRB_WIDTH : INTEGER range 63 downto 0 := 4;
    constant C_S_AXI_ADDR_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant C_M_AXI_ID_WIDTH : INTEGER range 63 downto 0 := 1;
    constant C_M_AXI_ADDR_WIDTH : INTEGER range 63 downto 0 := 20;
    constant C_M_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant C_M_AXI_WSTRB_WIDTH : INTEGER range 63 downto 0 := 4;
    constant C_M_AXI_AWUSER_WIDTH : INTEGER range 63 downto 0 := 1;
    constant C_M_AXI_ARUSER_WIDTH : INTEGER range 63 downto 0 := 1;
    constant C_M_AXI_WUSER_WIDTH : INTEGER range 63 downto 0 := 1;
    constant C_M_AXI_RUSER_WIDTH : INTEGER range 63 downto 0 := 1;
    constant C_M_AXI_BUSER_WIDTH : INTEGER range 63 downto 0 := 1;
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_ready : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal direction : STD_LOGIC;
    signal in_M_real_V : STD_LOGIC_VECTOR (31 downto 0);
    signal in_M_imag_V : STD_LOGIC_VECTOR (31 downto 0);
    signal out_M_real_V : STD_LOGIC_VECTOR (31 downto 0);
    signal out_M_imag_V : STD_LOGIC_VECTOR (31 downto 0);
    signal mem_bus_AWREADY : STD_LOGIC;
    signal mem_bus_WREADY : STD_LOGIC;
    signal mem_bus_ARREADY : STD_LOGIC;
    signal mem_bus_RVALID : STD_LOGIC;
    signal mem_bus_RDATA : STD_LOGIC_VECTOR (15 downto 0);
    signal mem_bus_RLAST : STD_LOGIC;
    signal mem_bus_RID : STD_LOGIC_VECTOR (0 downto 0);
    signal mem_bus_RUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal mem_bus_RRESP : STD_LOGIC_VECTOR (1 downto 0);
    signal mem_bus_BVALID : STD_LOGIC;
    signal mem_bus_BRESP : STD_LOGIC_VECTOR (1 downto 0);
    signal mem_bus_BID : STD_LOGIC_VECTOR (0 downto 0);
    signal mem_bus_BUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal dummy_proc_fe11_U0_ap_start : STD_LOGIC;
    signal dummy_proc_fe11_U0_start_full_n : STD_LOGIC;
    signal dummy_proc_fe11_U0_ap_done : STD_LOGIC;
    signal dummy_proc_fe11_U0_ap_continue : STD_LOGIC;
    signal dummy_proc_fe11_U0_ap_idle : STD_LOGIC;
    signal dummy_proc_fe11_U0_ap_ready : STD_LOGIC;
    signal dummy_proc_fe11_U0_start_out : STD_LOGIC;
    signal dummy_proc_fe11_U0_start_write : STD_LOGIC;
    signal dummy_proc_fe11_U0_direction : STD_LOGIC_VECTOR (0 downto 0);
    signal dummy_proc_fe11_U0_config_data_V_2_din : STD_LOGIC_VECTOR (15 downto 0);
    signal dummy_proc_fe11_U0_config_data_V_2_write : STD_LOGIC;
    signal dummy_proc_fe11_U0_config_data_V_din : STD_LOGIC_VECTOR (15 downto 0);
    signal dummy_proc_fe11_U0_config_data_V_write : STD_LOGIC;
    signal dummy_proc_fe11_U0_m_axi_in_M_real_V_AWVALID : STD_LOGIC;
    signal dummy_proc_fe11_U0_m_axi_in_M_real_V_AWADDR : STD_LOGIC_VECTOR (31 downto 0);
    signal dummy_proc_fe11_U0_m_axi_in_M_real_V_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal dummy_proc_fe11_U0_m_axi_in_M_real_V_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal dummy_proc_fe11_U0_m_axi_in_M_real_V_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal dummy_proc_fe11_U0_m_axi_in_M_real_V_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal dummy_proc_fe11_U0_m_axi_in_M_real_V_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal dummy_proc_fe11_U0_m_axi_in_M_real_V_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal dummy_proc_fe11_U0_m_axi_in_M_real_V_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal dummy_proc_fe11_U0_m_axi_in_M_real_V_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal dummy_proc_fe11_U0_m_axi_in_M_real_V_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal dummy_proc_fe11_U0_m_axi_in_M_real_V_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal dummy_proc_fe11_U0_m_axi_in_M_real_V_WVALID : STD_LOGIC;
    signal dummy_proc_fe11_U0_m_axi_in_M_real_V_WDATA : STD_LOGIC_VECTOR (15 downto 0);
    signal dummy_proc_fe11_U0_m_axi_in_M_real_V_WSTRB : STD_LOGIC_VECTOR (1 downto 0);
    signal dummy_proc_fe11_U0_m_axi_in_M_real_V_WLAST : STD_LOGIC;
    signal dummy_proc_fe11_U0_m_axi_in_M_real_V_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal dummy_proc_fe11_U0_m_axi_in_M_real_V_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal dummy_proc_fe11_U0_m_axi_in_M_real_V_ARVALID : STD_LOGIC;
    signal dummy_proc_fe11_U0_m_axi_in_M_real_V_ARADDR : STD_LOGIC_VECTOR (31 downto 0);
    signal dummy_proc_fe11_U0_m_axi_in_M_real_V_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal dummy_proc_fe11_U0_m_axi_in_M_real_V_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal dummy_proc_fe11_U0_m_axi_in_M_real_V_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal dummy_proc_fe11_U0_m_axi_in_M_real_V_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal dummy_proc_fe11_U0_m_axi_in_M_real_V_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal dummy_proc_fe11_U0_m_axi_in_M_real_V_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal dummy_proc_fe11_U0_m_axi_in_M_real_V_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal dummy_proc_fe11_U0_m_axi_in_M_real_V_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal dummy_proc_fe11_U0_m_axi_in_M_real_V_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal dummy_proc_fe11_U0_m_axi_in_M_real_V_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal dummy_proc_fe11_U0_m_axi_in_M_real_V_RREADY : STD_LOGIC;
    signal dummy_proc_fe11_U0_m_axi_in_M_real_V_BREADY : STD_LOGIC;
    signal dummy_proc_fe11_U0_out_r_din : STD_LOGIC_VECTOR (31 downto 0);
    signal dummy_proc_fe11_U0_out_r_write : STD_LOGIC;
    signal dummy_proc_fe11_U0_out_M_real_V_out_din : STD_LOGIC_VECTOR (31 downto 0);
    signal dummy_proc_fe11_U0_out_M_real_V_out_write : STD_LOGIC;
    signal dummy_proc_fe11_U0_out_M_imag_V_out_din : STD_LOGIC_VECTOR (31 downto 0);
    signal dummy_proc_fe11_U0_out_M_imag_V_out_write : STD_LOGIC;
    signal fft_config1_U0_ap_start : STD_LOGIC;
    signal fft_config1_U0_ap_done : STD_LOGIC;
    signal fft_config1_U0_ap_idle : STD_LOGIC;
    signal fft_config1_U0_ap_ready : STD_LOGIC;
    signal fft_config1_U0_ap_continue : STD_LOGIC;
    signal fft_config1_U0_xn_read : STD_LOGIC;
    signal fft_config1_U0_xk_din : STD_LOGIC_VECTOR (31 downto 0);
    signal fft_config1_U0_xk_write : STD_LOGIC;
    signal fft_config1_U0_status_data_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal fft_config1_U0_status_data_V_write : STD_LOGIC;
    signal fft_config1_U0_config_ch_data_V_read : STD_LOGIC;
    signal dummy_proc_middle_U0_ap_start : STD_LOGIC;
    signal dummy_proc_middle_U0_ap_done : STD_LOGIC;
    signal dummy_proc_middle_U0_ap_continue : STD_LOGIC;
    signal dummy_proc_middle_U0_ap_idle : STD_LOGIC;
    signal dummy_proc_middle_U0_ap_ready : STD_LOGIC;
    signal dummy_proc_middle_U0_start_out : STD_LOGIC;
    signal dummy_proc_middle_U0_start_write : STD_LOGIC;
    signal dummy_proc_middle_U0_config_in_data_V_read : STD_LOGIC;
    signal dummy_proc_middle_U0_config_out_data_V_din : STD_LOGIC_VECTOR (15 downto 0);
    signal dummy_proc_middle_U0_config_out_data_V_write : STD_LOGIC;
    signal dummy_proc_middle_U0_st_in_data_V_read : STD_LOGIC;
    signal dummy_proc_middle_U0_in_r_read : STD_LOGIC;
    signal dummy_proc_middle_U0_out_r_din : STD_LOGIC_VECTOR (31 downto 0);
    signal dummy_proc_middle_U0_out_r_write : STD_LOGIC;
    signal fft_config1_1_U0_ap_start : STD_LOGIC;
    signal fft_config1_1_U0_ap_done : STD_LOGIC;
    signal fft_config1_1_U0_ap_idle : STD_LOGIC;
    signal fft_config1_1_U0_ap_ready : STD_LOGIC;
    signal fft_config1_1_U0_ap_continue : STD_LOGIC;
    signal fft_config1_1_U0_xn_read : STD_LOGIC;
    signal fft_config1_1_U0_xk_din : STD_LOGIC_VECTOR (31 downto 0);
    signal fft_config1_1_U0_xk_write : STD_LOGIC;
    signal fft_config1_1_U0_status_data_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal fft_config1_1_U0_status_data_V_write : STD_LOGIC;
    signal fft_config1_1_U0_config_ch_data_V_read : STD_LOGIC;
    signal dummy_proc_be_U0_ap_start : STD_LOGIC;
    signal dummy_proc_be_U0_ap_done : STD_LOGIC;
    signal dummy_proc_be_U0_ap_continue : STD_LOGIC;
    signal dummy_proc_be_U0_ap_idle : STD_LOGIC;
    signal dummy_proc_be_U0_ap_ready : STD_LOGIC;
    signal dummy_proc_be_U0_status_in_data_V_read : STD_LOGIC;
    signal dummy_proc_be_U0_ovflo : STD_LOGIC;
    signal dummy_proc_be_U0_ovflo_ap_vld : STD_LOGIC;
    signal dummy_proc_be_U0_in_r_read : STD_LOGIC;
    signal dummy_proc_be_U0_m_axi_out_M_real_V_AWVALID : STD_LOGIC;
    signal dummy_proc_be_U0_m_axi_out_M_real_V_AWADDR : STD_LOGIC_VECTOR (31 downto 0);
    signal dummy_proc_be_U0_m_axi_out_M_real_V_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal dummy_proc_be_U0_m_axi_out_M_real_V_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal dummy_proc_be_U0_m_axi_out_M_real_V_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal dummy_proc_be_U0_m_axi_out_M_real_V_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal dummy_proc_be_U0_m_axi_out_M_real_V_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal dummy_proc_be_U0_m_axi_out_M_real_V_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal dummy_proc_be_U0_m_axi_out_M_real_V_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal dummy_proc_be_U0_m_axi_out_M_real_V_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal dummy_proc_be_U0_m_axi_out_M_real_V_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal dummy_proc_be_U0_m_axi_out_M_real_V_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal dummy_proc_be_U0_m_axi_out_M_real_V_WVALID : STD_LOGIC;
    signal dummy_proc_be_U0_m_axi_out_M_real_V_WDATA : STD_LOGIC_VECTOR (15 downto 0);
    signal dummy_proc_be_U0_m_axi_out_M_real_V_WSTRB : STD_LOGIC_VECTOR (1 downto 0);
    signal dummy_proc_be_U0_m_axi_out_M_real_V_WLAST : STD_LOGIC;
    signal dummy_proc_be_U0_m_axi_out_M_real_V_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal dummy_proc_be_U0_m_axi_out_M_real_V_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal dummy_proc_be_U0_m_axi_out_M_real_V_ARVALID : STD_LOGIC;
    signal dummy_proc_be_U0_m_axi_out_M_real_V_ARADDR : STD_LOGIC_VECTOR (31 downto 0);
    signal dummy_proc_be_U0_m_axi_out_M_real_V_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal dummy_proc_be_U0_m_axi_out_M_real_V_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal dummy_proc_be_U0_m_axi_out_M_real_V_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal dummy_proc_be_U0_m_axi_out_M_real_V_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal dummy_proc_be_U0_m_axi_out_M_real_V_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal dummy_proc_be_U0_m_axi_out_M_real_V_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal dummy_proc_be_U0_m_axi_out_M_real_V_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal dummy_proc_be_U0_m_axi_out_M_real_V_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal dummy_proc_be_U0_m_axi_out_M_real_V_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal dummy_proc_be_U0_m_axi_out_M_real_V_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal dummy_proc_be_U0_m_axi_out_M_real_V_RREADY : STD_LOGIC;
    signal dummy_proc_be_U0_m_axi_out_M_real_V_BREADY : STD_LOGIC;
    signal dummy_proc_be_U0_out_M_real_V_offset_read : STD_LOGIC;
    signal dummy_proc_be_U0_out_M_imag_V_offset_read : STD_LOGIC;
    signal ap_sync_continue : STD_LOGIC;
    signal fft_config1_data_V_full_n : STD_LOGIC;
    signal fft_config1_data_V_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal fft_config1_data_V_empty_n : STD_LOGIC;
    signal fft_config1_data_V_c_full_n : STD_LOGIC;
    signal fft_config1_data_V_c_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal fft_config1_data_V_c_empty_n : STD_LOGIC;
    signal xn1_channel_full_n : STD_LOGIC;
    signal xn1_channel_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal xn1_channel_empty_n : STD_LOGIC;
    signal out_M_real_V_c_full_n : STD_LOGIC;
    signal out_M_real_V_c_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal out_M_real_V_c_empty_n : STD_LOGIC;
    signal out_M_imag_V_c_full_n : STD_LOGIC;
    signal out_M_imag_V_c_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal out_M_imag_V_c_empty_n : STD_LOGIC;
    signal xk1_channel_full_n : STD_LOGIC;
    signal xk1_channel_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal xk1_channel_empty_n : STD_LOGIC;
    signal fft_status1_data_V_full_n : STD_LOGIC;
    signal fft_status1_data_V_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal fft_status1_data_V_empty_n : STD_LOGIC;
    signal fft_config2_data_V_full_n : STD_LOGIC;
    signal fft_config2_data_V_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal fft_config2_data_V_empty_n : STD_LOGIC;
    signal xn2_channel_full_n : STD_LOGIC;
    signal xn2_channel_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal xn2_channel_empty_n : STD_LOGIC;
    signal xk2_channel_full_n : STD_LOGIC;
    signal xk2_channel_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal xk2_channel_empty_n : STD_LOGIC;
    signal fft_status2_data_V_full_n : STD_LOGIC;
    signal fft_status2_data_V_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal fft_status2_data_V_empty_n : STD_LOGIC;
    signal ap_sync_done : STD_LOGIC;
    signal ap_sync_ready : STD_LOGIC;
    signal start_for_fft_config1_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_fft_config1_U0_full_n : STD_LOGIC;
    signal start_for_fft_config1_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_fft_config1_U0_empty_n : STD_LOGIC;
    signal start_for_dummy_proc_middle_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_dummy_proc_middle_U0_full_n : STD_LOGIC;
    signal start_for_dummy_proc_middle_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_dummy_proc_middle_U0_empty_n : STD_LOGIC;
    signal start_for_dummy_proc_be_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_dummy_proc_be_U0_full_n : STD_LOGIC;
    signal start_for_dummy_proc_be_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_dummy_proc_be_U0_empty_n : STD_LOGIC;
    signal fft_config1_U0_start_full_n : STD_LOGIC;
    signal fft_config1_U0_start_write : STD_LOGIC;
    signal start_for_fft_config1_1_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_fft_config1_1_U0_full_n : STD_LOGIC;
    signal start_for_fft_config1_1_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_fft_config1_1_U0_empty_n : STD_LOGIC;
    signal fft_config1_1_U0_start_full_n : STD_LOGIC;
    signal fft_config1_1_U0_start_write : STD_LOGIC;
    signal dummy_proc_be_U0_start_full_n : STD_LOGIC;
    signal dummy_proc_be_U0_start_write : STD_LOGIC;

    component dummy_proc_fe11 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        direction : IN STD_LOGIC_VECTOR (0 downto 0);
        config_data_V_2_din : OUT STD_LOGIC_VECTOR (15 downto 0);
        config_data_V_2_full_n : IN STD_LOGIC;
        config_data_V_2_write : OUT STD_LOGIC;
        config_data_V_din : OUT STD_LOGIC_VECTOR (15 downto 0);
        config_data_V_full_n : IN STD_LOGIC;
        config_data_V_write : OUT STD_LOGIC;
        m_axi_in_M_real_V_AWVALID : OUT STD_LOGIC;
        m_axi_in_M_real_V_AWREADY : IN STD_LOGIC;
        m_axi_in_M_real_V_AWADDR : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_in_M_real_V_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_in_M_real_V_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_in_M_real_V_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_in_M_real_V_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_in_M_real_V_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_in_M_real_V_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_in_M_real_V_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_in_M_real_V_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_in_M_real_V_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_in_M_real_V_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_in_M_real_V_WVALID : OUT STD_LOGIC;
        m_axi_in_M_real_V_WREADY : IN STD_LOGIC;
        m_axi_in_M_real_V_WDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
        m_axi_in_M_real_V_WSTRB : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_in_M_real_V_WLAST : OUT STD_LOGIC;
        m_axi_in_M_real_V_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_in_M_real_V_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_in_M_real_V_ARVALID : OUT STD_LOGIC;
        m_axi_in_M_real_V_ARREADY : IN STD_LOGIC;
        m_axi_in_M_real_V_ARADDR : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_in_M_real_V_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_in_M_real_V_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_in_M_real_V_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_in_M_real_V_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_in_M_real_V_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_in_M_real_V_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_in_M_real_V_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_in_M_real_V_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_in_M_real_V_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_in_M_real_V_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_in_M_real_V_RVALID : IN STD_LOGIC;
        m_axi_in_M_real_V_RREADY : OUT STD_LOGIC;
        m_axi_in_M_real_V_RDATA : IN STD_LOGIC_VECTOR (15 downto 0);
        m_axi_in_M_real_V_RLAST : IN STD_LOGIC;
        m_axi_in_M_real_V_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_in_M_real_V_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_in_M_real_V_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_in_M_real_V_BVALID : IN STD_LOGIC;
        m_axi_in_M_real_V_BREADY : OUT STD_LOGIC;
        m_axi_in_M_real_V_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_in_M_real_V_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_in_M_real_V_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        in_M_real_V_offset : IN STD_LOGIC_VECTOR (31 downto 0);
        in_M_imag_V_offset : IN STD_LOGIC_VECTOR (31 downto 0);
        out_r_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        out_r_full_n : IN STD_LOGIC;
        out_r_write : OUT STD_LOGIC;
        out_M_real_V : IN STD_LOGIC_VECTOR (31 downto 0);
        out_M_imag_V : IN STD_LOGIC_VECTOR (31 downto 0);
        out_M_real_V_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        out_M_real_V_out_full_n : IN STD_LOGIC;
        out_M_real_V_out_write : OUT STD_LOGIC;
        out_M_imag_V_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        out_M_imag_V_out_full_n : IN STD_LOGIC;
        out_M_imag_V_out_write : OUT STD_LOGIC );
    end component;


    component fft_config1_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ce : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        xn_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        xn_empty_n : IN STD_LOGIC;
        xn_read : OUT STD_LOGIC;
        xk_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        xk_full_n : IN STD_LOGIC;
        xk_write : OUT STD_LOGIC;
        status_data_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        status_data_V_full_n : IN STD_LOGIC;
        status_data_V_write : OUT STD_LOGIC;
        config_ch_data_V_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        config_ch_data_V_empty_n : IN STD_LOGIC;
        config_ch_data_V_read : OUT STD_LOGIC );
    end component;


    component dummy_proc_middle IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        config_in_data_V_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        config_in_data_V_empty_n : IN STD_LOGIC;
        config_in_data_V_read : OUT STD_LOGIC;
        config_out_data_V_din : OUT STD_LOGIC_VECTOR (15 downto 0);
        config_out_data_V_full_n : IN STD_LOGIC;
        config_out_data_V_write : OUT STD_LOGIC;
        st_in_data_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        st_in_data_V_empty_n : IN STD_LOGIC;
        st_in_data_V_read : OUT STD_LOGIC;
        in_r_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        in_r_empty_n : IN STD_LOGIC;
        in_r_read : OUT STD_LOGIC;
        out_r_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        out_r_full_n : IN STD_LOGIC;
        out_r_write : OUT STD_LOGIC );
    end component;


    component fft_config1_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ce : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        xn_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        xn_empty_n : IN STD_LOGIC;
        xn_read : OUT STD_LOGIC;
        xk_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        xk_full_n : IN STD_LOGIC;
        xk_write : OUT STD_LOGIC;
        status_data_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        status_data_V_full_n : IN STD_LOGIC;
        status_data_V_write : OUT STD_LOGIC;
        config_ch_data_V_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        config_ch_data_V_empty_n : IN STD_LOGIC;
        config_ch_data_V_read : OUT STD_LOGIC );
    end component;


    component dummy_proc_be IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        status_in_data_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        status_in_data_V_empty_n : IN STD_LOGIC;
        status_in_data_V_read : OUT STD_LOGIC;
        ovflo : OUT STD_LOGIC;
        ovflo_ap_vld : OUT STD_LOGIC;
        in_r_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        in_r_empty_n : IN STD_LOGIC;
        in_r_read : OUT STD_LOGIC;
        m_axi_out_M_real_V_AWVALID : OUT STD_LOGIC;
        m_axi_out_M_real_V_AWREADY : IN STD_LOGIC;
        m_axi_out_M_real_V_AWADDR : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_out_M_real_V_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_out_M_real_V_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_out_M_real_V_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_out_M_real_V_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_out_M_real_V_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_out_M_real_V_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_out_M_real_V_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_out_M_real_V_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_out_M_real_V_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_out_M_real_V_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_out_M_real_V_WVALID : OUT STD_LOGIC;
        m_axi_out_M_real_V_WREADY : IN STD_LOGIC;
        m_axi_out_M_real_V_WDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
        m_axi_out_M_real_V_WSTRB : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_out_M_real_V_WLAST : OUT STD_LOGIC;
        m_axi_out_M_real_V_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_out_M_real_V_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_out_M_real_V_ARVALID : OUT STD_LOGIC;
        m_axi_out_M_real_V_ARREADY : IN STD_LOGIC;
        m_axi_out_M_real_V_ARADDR : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_out_M_real_V_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_out_M_real_V_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_out_M_real_V_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_out_M_real_V_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_out_M_real_V_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_out_M_real_V_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_out_M_real_V_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_out_M_real_V_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_out_M_real_V_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_out_M_real_V_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_out_M_real_V_RVALID : IN STD_LOGIC;
        m_axi_out_M_real_V_RREADY : OUT STD_LOGIC;
        m_axi_out_M_real_V_RDATA : IN STD_LOGIC_VECTOR (15 downto 0);
        m_axi_out_M_real_V_RLAST : IN STD_LOGIC;
        m_axi_out_M_real_V_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_out_M_real_V_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_out_M_real_V_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_out_M_real_V_BVALID : IN STD_LOGIC;
        m_axi_out_M_real_V_BREADY : OUT STD_LOGIC;
        m_axi_out_M_real_V_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_out_M_real_V_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_out_M_real_V_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        out_M_real_V_offset_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        out_M_real_V_offset_empty_n : IN STD_LOGIC;
        out_M_real_V_offset_read : OUT STD_LOGIC;
        out_M_imag_V_offset_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        out_M_imag_V_offset_empty_n : IN STD_LOGIC;
        out_M_imag_V_offset_read : OUT STD_LOGIC );
    end component;


    component fifo_w16_d2_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (15 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (15 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component fifo_w32_d1024_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (31 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (31 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component fifo_w32_d5_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (31 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (31 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component fifo_w8_d2_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (7 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (7 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component start_for_fft_config1_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component start_for_dummy_proc_middle_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component start_for_dummy_proc_be_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component start_for_fft_config1_1_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component fft_top_ctrl_bus_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC;
        direction : OUT STD_LOGIC;
        in_M_real_V : OUT STD_LOGIC_VECTOR (31 downto 0);
        in_M_imag_V : OUT STD_LOGIC_VECTOR (31 downto 0);
        out_M_real_V : OUT STD_LOGIC_VECTOR (31 downto 0);
        out_M_imag_V : OUT STD_LOGIC_VECTOR (31 downto 0);
        ovflo : IN STD_LOGIC;
        ovflo_ap_vld : IN STD_LOGIC );
    end component;


    component fft_top_mem_bus_m_axi IS
    generic (
        CONSERVATIVE : INTEGER;
        USER_DW : INTEGER;
        USER_AW : INTEGER;
        USER_MAXREQS : INTEGER;
        NUM_READ_OUTSTANDING : INTEGER;
        NUM_WRITE_OUTSTANDING : INTEGER;
        MAX_READ_BURST_LENGTH : INTEGER;
        MAX_WRITE_BURST_LENGTH : INTEGER;
        C_M_AXI_ID_WIDTH : INTEGER;
        C_M_AXI_ADDR_WIDTH : INTEGER;
        C_M_AXI_DATA_WIDTH : INTEGER;
        C_M_AXI_AWUSER_WIDTH : INTEGER;
        C_M_AXI_ARUSER_WIDTH : INTEGER;
        C_M_AXI_WUSER_WIDTH : INTEGER;
        C_M_AXI_RUSER_WIDTH : INTEGER;
        C_M_AXI_BUSER_WIDTH : INTEGER;
        C_USER_VALUE : INTEGER;
        C_PROT_VALUE : INTEGER;
        C_CACHE_VALUE : INTEGER );
    port (
        AWVALID : OUT STD_LOGIC;
        AWREADY : IN STD_LOGIC;
        AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_AWUSER_WIDTH-1 downto 0);
        WVALID : OUT STD_LOGIC;
        WREADY : IN STD_LOGIC;
        WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH/8-1 downto 0);
        WLAST : OUT STD_LOGIC;
        WID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_WUSER_WIDTH-1 downto 0);
        ARVALID : OUT STD_LOGIC;
        ARREADY : IN STD_LOGIC;
        ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_ARUSER_WIDTH-1 downto 0);
        RVALID : IN STD_LOGIC;
        RREADY : OUT STD_LOGIC;
        RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        RLAST : IN STD_LOGIC;
        RID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_RUSER_WIDTH-1 downto 0);
        RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BVALID : IN STD_LOGIC;
        BREADY : OUT STD_LOGIC;
        BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_BUSER_WIDTH-1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        I_ARVALID : IN STD_LOGIC;
        I_ARREADY : OUT STD_LOGIC;
        I_ARADDR : IN STD_LOGIC_VECTOR (31 downto 0);
        I_ARID : IN STD_LOGIC_VECTOR (0 downto 0);
        I_ARLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_ARSIZE : IN STD_LOGIC_VECTOR (2 downto 0);
        I_ARLOCK : IN STD_LOGIC_VECTOR (1 downto 0);
        I_ARCACHE : IN STD_LOGIC_VECTOR (3 downto 0);
        I_ARQOS : IN STD_LOGIC_VECTOR (3 downto 0);
        I_ARPROT : IN STD_LOGIC_VECTOR (2 downto 0);
        I_ARUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        I_ARBURST : IN STD_LOGIC_VECTOR (1 downto 0);
        I_ARREGION : IN STD_LOGIC_VECTOR (3 downto 0);
        I_RVALID : OUT STD_LOGIC;
        I_RREADY : IN STD_LOGIC;
        I_RDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
        I_RID : OUT STD_LOGIC_VECTOR (0 downto 0);
        I_RUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        I_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        I_RLAST : OUT STD_LOGIC;
        I_AWVALID : IN STD_LOGIC;
        I_AWREADY : OUT STD_LOGIC;
        I_AWADDR : IN STD_LOGIC_VECTOR (31 downto 0);
        I_AWID : IN STD_LOGIC_VECTOR (0 downto 0);
        I_AWLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_AWSIZE : IN STD_LOGIC_VECTOR (2 downto 0);
        I_AWLOCK : IN STD_LOGIC_VECTOR (1 downto 0);
        I_AWCACHE : IN STD_LOGIC_VECTOR (3 downto 0);
        I_AWQOS : IN STD_LOGIC_VECTOR (3 downto 0);
        I_AWPROT : IN STD_LOGIC_VECTOR (2 downto 0);
        I_AWUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        I_AWBURST : IN STD_LOGIC_VECTOR (1 downto 0);
        I_AWREGION : IN STD_LOGIC_VECTOR (3 downto 0);
        I_WVALID : IN STD_LOGIC;
        I_WREADY : OUT STD_LOGIC;
        I_WDATA : IN STD_LOGIC_VECTOR (15 downto 0);
        I_WID : IN STD_LOGIC_VECTOR (0 downto 0);
        I_WUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        I_WLAST : IN STD_LOGIC;
        I_WSTRB : IN STD_LOGIC_VECTOR (1 downto 0);
        I_BVALID : OUT STD_LOGIC;
        I_BREADY : IN STD_LOGIC;
        I_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        I_BID : OUT STD_LOGIC_VECTOR (0 downto 0);
        I_BUSER : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;



begin
    fft_top_ctrl_bus_s_axi_U : component fft_top_ctrl_bus_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CTRL_BUS_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CTRL_BUS_DATA_WIDTH)
    port map (
        AWVALID => s_axi_ctrl_bus_AWVALID,
        AWREADY => s_axi_ctrl_bus_AWREADY,
        AWADDR => s_axi_ctrl_bus_AWADDR,
        WVALID => s_axi_ctrl_bus_WVALID,
        WREADY => s_axi_ctrl_bus_WREADY,
        WDATA => s_axi_ctrl_bus_WDATA,
        WSTRB => s_axi_ctrl_bus_WSTRB,
        ARVALID => s_axi_ctrl_bus_ARVALID,
        ARREADY => s_axi_ctrl_bus_ARREADY,
        ARADDR => s_axi_ctrl_bus_ARADDR,
        RVALID => s_axi_ctrl_bus_RVALID,
        RREADY => s_axi_ctrl_bus_RREADY,
        RDATA => s_axi_ctrl_bus_RDATA,
        RRESP => s_axi_ctrl_bus_RRESP,
        BVALID => s_axi_ctrl_bus_BVALID,
        BREADY => s_axi_ctrl_bus_BREADY,
        BRESP => s_axi_ctrl_bus_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle,
        direction => direction,
        in_M_real_V => in_M_real_V,
        in_M_imag_V => in_M_imag_V,
        out_M_real_V => out_M_real_V,
        out_M_imag_V => out_M_imag_V,
        ovflo => dummy_proc_be_U0_ovflo,
        ovflo_ap_vld => dummy_proc_be_U0_ovflo_ap_vld);

    fft_top_mem_bus_m_axi_U : component fft_top_mem_bus_m_axi
    generic map (
        CONSERVATIVE => 0,
        USER_DW => 16,
        USER_AW => 32,
        USER_MAXREQS => 5,
        NUM_READ_OUTSTANDING => 16,
        NUM_WRITE_OUTSTANDING => 16,
        MAX_READ_BURST_LENGTH => 16,
        MAX_WRITE_BURST_LENGTH => 16,
        C_M_AXI_ID_WIDTH => C_M_AXI_MEM_BUS_ID_WIDTH,
        C_M_AXI_ADDR_WIDTH => C_M_AXI_MEM_BUS_ADDR_WIDTH,
        C_M_AXI_DATA_WIDTH => C_M_AXI_MEM_BUS_DATA_WIDTH,
        C_M_AXI_AWUSER_WIDTH => C_M_AXI_MEM_BUS_AWUSER_WIDTH,
        C_M_AXI_ARUSER_WIDTH => C_M_AXI_MEM_BUS_ARUSER_WIDTH,
        C_M_AXI_WUSER_WIDTH => C_M_AXI_MEM_BUS_WUSER_WIDTH,
        C_M_AXI_RUSER_WIDTH => C_M_AXI_MEM_BUS_RUSER_WIDTH,
        C_M_AXI_BUSER_WIDTH => C_M_AXI_MEM_BUS_BUSER_WIDTH,
        C_USER_VALUE => C_M_AXI_MEM_BUS_USER_VALUE,
        C_PROT_VALUE => C_M_AXI_MEM_BUS_PROT_VALUE,
        C_CACHE_VALUE => C_M_AXI_MEM_BUS_CACHE_VALUE)
    port map (
        AWVALID => m_axi_mem_bus_AWVALID,
        AWREADY => m_axi_mem_bus_AWREADY,
        AWADDR => m_axi_mem_bus_AWADDR,
        AWID => m_axi_mem_bus_AWID,
        AWLEN => m_axi_mem_bus_AWLEN,
        AWSIZE => m_axi_mem_bus_AWSIZE,
        AWBURST => m_axi_mem_bus_AWBURST,
        AWLOCK => m_axi_mem_bus_AWLOCK,
        AWCACHE => m_axi_mem_bus_AWCACHE,
        AWPROT => m_axi_mem_bus_AWPROT,
        AWQOS => m_axi_mem_bus_AWQOS,
        AWREGION => m_axi_mem_bus_AWREGION,
        AWUSER => m_axi_mem_bus_AWUSER,
        WVALID => m_axi_mem_bus_WVALID,
        WREADY => m_axi_mem_bus_WREADY,
        WDATA => m_axi_mem_bus_WDATA,
        WSTRB => m_axi_mem_bus_WSTRB,
        WLAST => m_axi_mem_bus_WLAST,
        WID => m_axi_mem_bus_WID,
        WUSER => m_axi_mem_bus_WUSER,
        ARVALID => m_axi_mem_bus_ARVALID,
        ARREADY => m_axi_mem_bus_ARREADY,
        ARADDR => m_axi_mem_bus_ARADDR,
        ARID => m_axi_mem_bus_ARID,
        ARLEN => m_axi_mem_bus_ARLEN,
        ARSIZE => m_axi_mem_bus_ARSIZE,
        ARBURST => m_axi_mem_bus_ARBURST,
        ARLOCK => m_axi_mem_bus_ARLOCK,
        ARCACHE => m_axi_mem_bus_ARCACHE,
        ARPROT => m_axi_mem_bus_ARPROT,
        ARQOS => m_axi_mem_bus_ARQOS,
        ARREGION => m_axi_mem_bus_ARREGION,
        ARUSER => m_axi_mem_bus_ARUSER,
        RVALID => m_axi_mem_bus_RVALID,
        RREADY => m_axi_mem_bus_RREADY,
        RDATA => m_axi_mem_bus_RDATA,
        RLAST => m_axi_mem_bus_RLAST,
        RID => m_axi_mem_bus_RID,
        RUSER => m_axi_mem_bus_RUSER,
        RRESP => m_axi_mem_bus_RRESP,
        BVALID => m_axi_mem_bus_BVALID,
        BREADY => m_axi_mem_bus_BREADY,
        BRESP => m_axi_mem_bus_BRESP,
        BID => m_axi_mem_bus_BID,
        BUSER => m_axi_mem_bus_BUSER,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        I_ARVALID => dummy_proc_fe11_U0_m_axi_in_M_real_V_ARVALID,
        I_ARREADY => mem_bus_ARREADY,
        I_ARADDR => dummy_proc_fe11_U0_m_axi_in_M_real_V_ARADDR,
        I_ARID => dummy_proc_fe11_U0_m_axi_in_M_real_V_ARID,
        I_ARLEN => dummy_proc_fe11_U0_m_axi_in_M_real_V_ARLEN,
        I_ARSIZE => dummy_proc_fe11_U0_m_axi_in_M_real_V_ARSIZE,
        I_ARLOCK => dummy_proc_fe11_U0_m_axi_in_M_real_V_ARLOCK,
        I_ARCACHE => dummy_proc_fe11_U0_m_axi_in_M_real_V_ARCACHE,
        I_ARQOS => dummy_proc_fe11_U0_m_axi_in_M_real_V_ARQOS,
        I_ARPROT => dummy_proc_fe11_U0_m_axi_in_M_real_V_ARPROT,
        I_ARUSER => dummy_proc_fe11_U0_m_axi_in_M_real_V_ARUSER,
        I_ARBURST => dummy_proc_fe11_U0_m_axi_in_M_real_V_ARBURST,
        I_ARREGION => dummy_proc_fe11_U0_m_axi_in_M_real_V_ARREGION,
        I_RVALID => mem_bus_RVALID,
        I_RREADY => dummy_proc_fe11_U0_m_axi_in_M_real_V_RREADY,
        I_RDATA => mem_bus_RDATA,
        I_RID => mem_bus_RID,
        I_RUSER => mem_bus_RUSER,
        I_RRESP => mem_bus_RRESP,
        I_RLAST => mem_bus_RLAST,
        I_AWVALID => dummy_proc_be_U0_m_axi_out_M_real_V_AWVALID,
        I_AWREADY => mem_bus_AWREADY,
        I_AWADDR => dummy_proc_be_U0_m_axi_out_M_real_V_AWADDR,
        I_AWID => dummy_proc_be_U0_m_axi_out_M_real_V_AWID,
        I_AWLEN => dummy_proc_be_U0_m_axi_out_M_real_V_AWLEN,
        I_AWSIZE => dummy_proc_be_U0_m_axi_out_M_real_V_AWSIZE,
        I_AWLOCK => dummy_proc_be_U0_m_axi_out_M_real_V_AWLOCK,
        I_AWCACHE => dummy_proc_be_U0_m_axi_out_M_real_V_AWCACHE,
        I_AWQOS => dummy_proc_be_U0_m_axi_out_M_real_V_AWQOS,
        I_AWPROT => dummy_proc_be_U0_m_axi_out_M_real_V_AWPROT,
        I_AWUSER => dummy_proc_be_U0_m_axi_out_M_real_V_AWUSER,
        I_AWBURST => dummy_proc_be_U0_m_axi_out_M_real_V_AWBURST,
        I_AWREGION => dummy_proc_be_U0_m_axi_out_M_real_V_AWREGION,
        I_WVALID => dummy_proc_be_U0_m_axi_out_M_real_V_WVALID,
        I_WREADY => mem_bus_WREADY,
        I_WDATA => dummy_proc_be_U0_m_axi_out_M_real_V_WDATA,
        I_WID => dummy_proc_be_U0_m_axi_out_M_real_V_WID,
        I_WUSER => dummy_proc_be_U0_m_axi_out_M_real_V_WUSER,
        I_WLAST => dummy_proc_be_U0_m_axi_out_M_real_V_WLAST,
        I_WSTRB => dummy_proc_be_U0_m_axi_out_M_real_V_WSTRB,
        I_BVALID => mem_bus_BVALID,
        I_BREADY => dummy_proc_be_U0_m_axi_out_M_real_V_BREADY,
        I_BRESP => mem_bus_BRESP,
        I_BID => mem_bus_BID,
        I_BUSER => mem_bus_BUSER);

    dummy_proc_fe11_U0 : component dummy_proc_fe11
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => dummy_proc_fe11_U0_ap_start,
        start_full_n => dummy_proc_fe11_U0_start_full_n,
        ap_done => dummy_proc_fe11_U0_ap_done,
        ap_continue => dummy_proc_fe11_U0_ap_continue,
        ap_idle => dummy_proc_fe11_U0_ap_idle,
        ap_ready => dummy_proc_fe11_U0_ap_ready,
        start_out => dummy_proc_fe11_U0_start_out,
        start_write => dummy_proc_fe11_U0_start_write,
        direction => dummy_proc_fe11_U0_direction,
        config_data_V_2_din => dummy_proc_fe11_U0_config_data_V_2_din,
        config_data_V_2_full_n => fft_config1_data_V_full_n,
        config_data_V_2_write => dummy_proc_fe11_U0_config_data_V_2_write,
        config_data_V_din => dummy_proc_fe11_U0_config_data_V_din,
        config_data_V_full_n => fft_config1_data_V_c_full_n,
        config_data_V_write => dummy_proc_fe11_U0_config_data_V_write,
        m_axi_in_M_real_V_AWVALID => dummy_proc_fe11_U0_m_axi_in_M_real_V_AWVALID,
        m_axi_in_M_real_V_AWREADY => ap_const_logic_0,
        m_axi_in_M_real_V_AWADDR => dummy_proc_fe11_U0_m_axi_in_M_real_V_AWADDR,
        m_axi_in_M_real_V_AWID => dummy_proc_fe11_U0_m_axi_in_M_real_V_AWID,
        m_axi_in_M_real_V_AWLEN => dummy_proc_fe11_U0_m_axi_in_M_real_V_AWLEN,
        m_axi_in_M_real_V_AWSIZE => dummy_proc_fe11_U0_m_axi_in_M_real_V_AWSIZE,
        m_axi_in_M_real_V_AWBURST => dummy_proc_fe11_U0_m_axi_in_M_real_V_AWBURST,
        m_axi_in_M_real_V_AWLOCK => dummy_proc_fe11_U0_m_axi_in_M_real_V_AWLOCK,
        m_axi_in_M_real_V_AWCACHE => dummy_proc_fe11_U0_m_axi_in_M_real_V_AWCACHE,
        m_axi_in_M_real_V_AWPROT => dummy_proc_fe11_U0_m_axi_in_M_real_V_AWPROT,
        m_axi_in_M_real_V_AWQOS => dummy_proc_fe11_U0_m_axi_in_M_real_V_AWQOS,
        m_axi_in_M_real_V_AWREGION => dummy_proc_fe11_U0_m_axi_in_M_real_V_AWREGION,
        m_axi_in_M_real_V_AWUSER => dummy_proc_fe11_U0_m_axi_in_M_real_V_AWUSER,
        m_axi_in_M_real_V_WVALID => dummy_proc_fe11_U0_m_axi_in_M_real_V_WVALID,
        m_axi_in_M_real_V_WREADY => ap_const_logic_0,
        m_axi_in_M_real_V_WDATA => dummy_proc_fe11_U0_m_axi_in_M_real_V_WDATA,
        m_axi_in_M_real_V_WSTRB => dummy_proc_fe11_U0_m_axi_in_M_real_V_WSTRB,
        m_axi_in_M_real_V_WLAST => dummy_proc_fe11_U0_m_axi_in_M_real_V_WLAST,
        m_axi_in_M_real_V_WID => dummy_proc_fe11_U0_m_axi_in_M_real_V_WID,
        m_axi_in_M_real_V_WUSER => dummy_proc_fe11_U0_m_axi_in_M_real_V_WUSER,
        m_axi_in_M_real_V_ARVALID => dummy_proc_fe11_U0_m_axi_in_M_real_V_ARVALID,
        m_axi_in_M_real_V_ARREADY => mem_bus_ARREADY,
        m_axi_in_M_real_V_ARADDR => dummy_proc_fe11_U0_m_axi_in_M_real_V_ARADDR,
        m_axi_in_M_real_V_ARID => dummy_proc_fe11_U0_m_axi_in_M_real_V_ARID,
        m_axi_in_M_real_V_ARLEN => dummy_proc_fe11_U0_m_axi_in_M_real_V_ARLEN,
        m_axi_in_M_real_V_ARSIZE => dummy_proc_fe11_U0_m_axi_in_M_real_V_ARSIZE,
        m_axi_in_M_real_V_ARBURST => dummy_proc_fe11_U0_m_axi_in_M_real_V_ARBURST,
        m_axi_in_M_real_V_ARLOCK => dummy_proc_fe11_U0_m_axi_in_M_real_V_ARLOCK,
        m_axi_in_M_real_V_ARCACHE => dummy_proc_fe11_U0_m_axi_in_M_real_V_ARCACHE,
        m_axi_in_M_real_V_ARPROT => dummy_proc_fe11_U0_m_axi_in_M_real_V_ARPROT,
        m_axi_in_M_real_V_ARQOS => dummy_proc_fe11_U0_m_axi_in_M_real_V_ARQOS,
        m_axi_in_M_real_V_ARREGION => dummy_proc_fe11_U0_m_axi_in_M_real_V_ARREGION,
        m_axi_in_M_real_V_ARUSER => dummy_proc_fe11_U0_m_axi_in_M_real_V_ARUSER,
        m_axi_in_M_real_V_RVALID => mem_bus_RVALID,
        m_axi_in_M_real_V_RREADY => dummy_proc_fe11_U0_m_axi_in_M_real_V_RREADY,
        m_axi_in_M_real_V_RDATA => mem_bus_RDATA,
        m_axi_in_M_real_V_RLAST => mem_bus_RLAST,
        m_axi_in_M_real_V_RID => mem_bus_RID,
        m_axi_in_M_real_V_RUSER => mem_bus_RUSER,
        m_axi_in_M_real_V_RRESP => mem_bus_RRESP,
        m_axi_in_M_real_V_BVALID => ap_const_logic_0,
        m_axi_in_M_real_V_BREADY => dummy_proc_fe11_U0_m_axi_in_M_real_V_BREADY,
        m_axi_in_M_real_V_BRESP => ap_const_lv2_0,
        m_axi_in_M_real_V_BID => ap_const_lv1_0,
        m_axi_in_M_real_V_BUSER => ap_const_lv1_0,
        in_M_real_V_offset => in_M_real_V,
        in_M_imag_V_offset => in_M_imag_V,
        out_r_din => dummy_proc_fe11_U0_out_r_din,
        out_r_full_n => xn1_channel_full_n,
        out_r_write => dummy_proc_fe11_U0_out_r_write,
        out_M_real_V => out_M_real_V,
        out_M_imag_V => out_M_imag_V,
        out_M_real_V_out_din => dummy_proc_fe11_U0_out_M_real_V_out_din,
        out_M_real_V_out_full_n => out_M_real_V_c_full_n,
        out_M_real_V_out_write => dummy_proc_fe11_U0_out_M_real_V_out_write,
        out_M_imag_V_out_din => dummy_proc_fe11_U0_out_M_imag_V_out_din,
        out_M_imag_V_out_full_n => out_M_imag_V_c_full_n,
        out_M_imag_V_out_write => dummy_proc_fe11_U0_out_M_imag_V_out_write);

    fft_config1_U0 : component fft_config1_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => fft_config1_U0_ap_start,
        ap_ce => ap_const_logic_1,
        ap_done => fft_config1_U0_ap_done,
        ap_idle => fft_config1_U0_ap_idle,
        ap_ready => fft_config1_U0_ap_ready,
        ap_continue => fft_config1_U0_ap_continue,
        xn_dout => xn1_channel_dout,
        xn_empty_n => xn1_channel_empty_n,
        xn_read => fft_config1_U0_xn_read,
        xk_din => fft_config1_U0_xk_din,
        xk_full_n => xk1_channel_full_n,
        xk_write => fft_config1_U0_xk_write,
        status_data_V_din => fft_config1_U0_status_data_V_din,
        status_data_V_full_n => fft_status1_data_V_full_n,
        status_data_V_write => fft_config1_U0_status_data_V_write,
        config_ch_data_V_dout => fft_config1_data_V_dout,
        config_ch_data_V_empty_n => fft_config1_data_V_empty_n,
        config_ch_data_V_read => fft_config1_U0_config_ch_data_V_read);

    dummy_proc_middle_U0 : component dummy_proc_middle
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => dummy_proc_middle_U0_ap_start,
        start_full_n => start_for_fft_config1_1_U0_full_n,
        ap_done => dummy_proc_middle_U0_ap_done,
        ap_continue => dummy_proc_middle_U0_ap_continue,
        ap_idle => dummy_proc_middle_U0_ap_idle,
        ap_ready => dummy_proc_middle_U0_ap_ready,
        start_out => dummy_proc_middle_U0_start_out,
        start_write => dummy_proc_middle_U0_start_write,
        config_in_data_V_dout => fft_config1_data_V_c_dout,
        config_in_data_V_empty_n => fft_config1_data_V_c_empty_n,
        config_in_data_V_read => dummy_proc_middle_U0_config_in_data_V_read,
        config_out_data_V_din => dummy_proc_middle_U0_config_out_data_V_din,
        config_out_data_V_full_n => fft_config2_data_V_full_n,
        config_out_data_V_write => dummy_proc_middle_U0_config_out_data_V_write,
        st_in_data_V_dout => fft_status1_data_V_dout,
        st_in_data_V_empty_n => fft_status1_data_V_empty_n,
        st_in_data_V_read => dummy_proc_middle_U0_st_in_data_V_read,
        in_r_dout => xk1_channel_dout,
        in_r_empty_n => xk1_channel_empty_n,
        in_r_read => dummy_proc_middle_U0_in_r_read,
        out_r_din => dummy_proc_middle_U0_out_r_din,
        out_r_full_n => xn2_channel_full_n,
        out_r_write => dummy_proc_middle_U0_out_r_write);

    fft_config1_1_U0 : component fft_config1_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => fft_config1_1_U0_ap_start,
        ap_ce => ap_const_logic_1,
        ap_done => fft_config1_1_U0_ap_done,
        ap_idle => fft_config1_1_U0_ap_idle,
        ap_ready => fft_config1_1_U0_ap_ready,
        ap_continue => fft_config1_1_U0_ap_continue,
        xn_dout => xn2_channel_dout,
        xn_empty_n => xn2_channel_empty_n,
        xn_read => fft_config1_1_U0_xn_read,
        xk_din => fft_config1_1_U0_xk_din,
        xk_full_n => xk2_channel_full_n,
        xk_write => fft_config1_1_U0_xk_write,
        status_data_V_din => fft_config1_1_U0_status_data_V_din,
        status_data_V_full_n => fft_status2_data_V_full_n,
        status_data_V_write => fft_config1_1_U0_status_data_V_write,
        config_ch_data_V_dout => fft_config2_data_V_dout,
        config_ch_data_V_empty_n => fft_config2_data_V_empty_n,
        config_ch_data_V_read => fft_config1_1_U0_config_ch_data_V_read);

    dummy_proc_be_U0 : component dummy_proc_be
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => dummy_proc_be_U0_ap_start,
        ap_done => dummy_proc_be_U0_ap_done,
        ap_continue => dummy_proc_be_U0_ap_continue,
        ap_idle => dummy_proc_be_U0_ap_idle,
        ap_ready => dummy_proc_be_U0_ap_ready,
        status_in_data_V_dout => fft_status2_data_V_dout,
        status_in_data_V_empty_n => fft_status2_data_V_empty_n,
        status_in_data_V_read => dummy_proc_be_U0_status_in_data_V_read,
        ovflo => dummy_proc_be_U0_ovflo,
        ovflo_ap_vld => dummy_proc_be_U0_ovflo_ap_vld,
        in_r_dout => xk2_channel_dout,
        in_r_empty_n => xk2_channel_empty_n,
        in_r_read => dummy_proc_be_U0_in_r_read,
        m_axi_out_M_real_V_AWVALID => dummy_proc_be_U0_m_axi_out_M_real_V_AWVALID,
        m_axi_out_M_real_V_AWREADY => mem_bus_AWREADY,
        m_axi_out_M_real_V_AWADDR => dummy_proc_be_U0_m_axi_out_M_real_V_AWADDR,
        m_axi_out_M_real_V_AWID => dummy_proc_be_U0_m_axi_out_M_real_V_AWID,
        m_axi_out_M_real_V_AWLEN => dummy_proc_be_U0_m_axi_out_M_real_V_AWLEN,
        m_axi_out_M_real_V_AWSIZE => dummy_proc_be_U0_m_axi_out_M_real_V_AWSIZE,
        m_axi_out_M_real_V_AWBURST => dummy_proc_be_U0_m_axi_out_M_real_V_AWBURST,
        m_axi_out_M_real_V_AWLOCK => dummy_proc_be_U0_m_axi_out_M_real_V_AWLOCK,
        m_axi_out_M_real_V_AWCACHE => dummy_proc_be_U0_m_axi_out_M_real_V_AWCACHE,
        m_axi_out_M_real_V_AWPROT => dummy_proc_be_U0_m_axi_out_M_real_V_AWPROT,
        m_axi_out_M_real_V_AWQOS => dummy_proc_be_U0_m_axi_out_M_real_V_AWQOS,
        m_axi_out_M_real_V_AWREGION => dummy_proc_be_U0_m_axi_out_M_real_V_AWREGION,
        m_axi_out_M_real_V_AWUSER => dummy_proc_be_U0_m_axi_out_M_real_V_AWUSER,
        m_axi_out_M_real_V_WVALID => dummy_proc_be_U0_m_axi_out_M_real_V_WVALID,
        m_axi_out_M_real_V_WREADY => mem_bus_WREADY,
        m_axi_out_M_real_V_WDATA => dummy_proc_be_U0_m_axi_out_M_real_V_WDATA,
        m_axi_out_M_real_V_WSTRB => dummy_proc_be_U0_m_axi_out_M_real_V_WSTRB,
        m_axi_out_M_real_V_WLAST => dummy_proc_be_U0_m_axi_out_M_real_V_WLAST,
        m_axi_out_M_real_V_WID => dummy_proc_be_U0_m_axi_out_M_real_V_WID,
        m_axi_out_M_real_V_WUSER => dummy_proc_be_U0_m_axi_out_M_real_V_WUSER,
        m_axi_out_M_real_V_ARVALID => dummy_proc_be_U0_m_axi_out_M_real_V_ARVALID,
        m_axi_out_M_real_V_ARREADY => ap_const_logic_0,
        m_axi_out_M_real_V_ARADDR => dummy_proc_be_U0_m_axi_out_M_real_V_ARADDR,
        m_axi_out_M_real_V_ARID => dummy_proc_be_U0_m_axi_out_M_real_V_ARID,
        m_axi_out_M_real_V_ARLEN => dummy_proc_be_U0_m_axi_out_M_real_V_ARLEN,
        m_axi_out_M_real_V_ARSIZE => dummy_proc_be_U0_m_axi_out_M_real_V_ARSIZE,
        m_axi_out_M_real_V_ARBURST => dummy_proc_be_U0_m_axi_out_M_real_V_ARBURST,
        m_axi_out_M_real_V_ARLOCK => dummy_proc_be_U0_m_axi_out_M_real_V_ARLOCK,
        m_axi_out_M_real_V_ARCACHE => dummy_proc_be_U0_m_axi_out_M_real_V_ARCACHE,
        m_axi_out_M_real_V_ARPROT => dummy_proc_be_U0_m_axi_out_M_real_V_ARPROT,
        m_axi_out_M_real_V_ARQOS => dummy_proc_be_U0_m_axi_out_M_real_V_ARQOS,
        m_axi_out_M_real_V_ARREGION => dummy_proc_be_U0_m_axi_out_M_real_V_ARREGION,
        m_axi_out_M_real_V_ARUSER => dummy_proc_be_U0_m_axi_out_M_real_V_ARUSER,
        m_axi_out_M_real_V_RVALID => ap_const_logic_0,
        m_axi_out_M_real_V_RREADY => dummy_proc_be_U0_m_axi_out_M_real_V_RREADY,
        m_axi_out_M_real_V_RDATA => ap_const_lv16_0,
        m_axi_out_M_real_V_RLAST => ap_const_logic_0,
        m_axi_out_M_real_V_RID => ap_const_lv1_0,
        m_axi_out_M_real_V_RUSER => ap_const_lv1_0,
        m_axi_out_M_real_V_RRESP => ap_const_lv2_0,
        m_axi_out_M_real_V_BVALID => mem_bus_BVALID,
        m_axi_out_M_real_V_BREADY => dummy_proc_be_U0_m_axi_out_M_real_V_BREADY,
        m_axi_out_M_real_V_BRESP => mem_bus_BRESP,
        m_axi_out_M_real_V_BID => mem_bus_BID,
        m_axi_out_M_real_V_BUSER => mem_bus_BUSER,
        out_M_real_V_offset_dout => out_M_real_V_c_dout,
        out_M_real_V_offset_empty_n => out_M_real_V_c_empty_n,
        out_M_real_V_offset_read => dummy_proc_be_U0_out_M_real_V_offset_read,
        out_M_imag_V_offset_dout => out_M_imag_V_c_dout,
        out_M_imag_V_offset_empty_n => out_M_imag_V_c_empty_n,
        out_M_imag_V_offset_read => dummy_proc_be_U0_out_M_imag_V_offset_read);

    fft_config1_data_V_U : component fifo_w16_d2_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => dummy_proc_fe11_U0_config_data_V_2_din,
        if_full_n => fft_config1_data_V_full_n,
        if_write => dummy_proc_fe11_U0_config_data_V_2_write,
        if_dout => fft_config1_data_V_dout,
        if_empty_n => fft_config1_data_V_empty_n,
        if_read => fft_config1_U0_config_ch_data_V_read);

    fft_config1_data_V_c_U : component fifo_w16_d2_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => dummy_proc_fe11_U0_config_data_V_din,
        if_full_n => fft_config1_data_V_c_full_n,
        if_write => dummy_proc_fe11_U0_config_data_V_write,
        if_dout => fft_config1_data_V_c_dout,
        if_empty_n => fft_config1_data_V_c_empty_n,
        if_read => dummy_proc_middle_U0_config_in_data_V_read);

    xn1_channel_U : component fifo_w32_d1024_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => dummy_proc_fe11_U0_out_r_din,
        if_full_n => xn1_channel_full_n,
        if_write => dummy_proc_fe11_U0_out_r_write,
        if_dout => xn1_channel_dout,
        if_empty_n => xn1_channel_empty_n,
        if_read => fft_config1_U0_xn_read);

    out_M_real_V_c_U : component fifo_w32_d5_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => dummy_proc_fe11_U0_out_M_real_V_out_din,
        if_full_n => out_M_real_V_c_full_n,
        if_write => dummy_proc_fe11_U0_out_M_real_V_out_write,
        if_dout => out_M_real_V_c_dout,
        if_empty_n => out_M_real_V_c_empty_n,
        if_read => dummy_proc_be_U0_out_M_real_V_offset_read);

    out_M_imag_V_c_U : component fifo_w32_d5_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => dummy_proc_fe11_U0_out_M_imag_V_out_din,
        if_full_n => out_M_imag_V_c_full_n,
        if_write => dummy_proc_fe11_U0_out_M_imag_V_out_write,
        if_dout => out_M_imag_V_c_dout,
        if_empty_n => out_M_imag_V_c_empty_n,
        if_read => dummy_proc_be_U0_out_M_imag_V_offset_read);

    xk1_channel_U : component fifo_w32_d1024_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => fft_config1_U0_xk_din,
        if_full_n => xk1_channel_full_n,
        if_write => fft_config1_U0_xk_write,
        if_dout => xk1_channel_dout,
        if_empty_n => xk1_channel_empty_n,
        if_read => dummy_proc_middle_U0_in_r_read);

    fft_status1_data_V_U : component fifo_w8_d2_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => fft_config1_U0_status_data_V_din,
        if_full_n => fft_status1_data_V_full_n,
        if_write => fft_config1_U0_status_data_V_write,
        if_dout => fft_status1_data_V_dout,
        if_empty_n => fft_status1_data_V_empty_n,
        if_read => dummy_proc_middle_U0_st_in_data_V_read);

    fft_config2_data_V_U : component fifo_w16_d2_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => dummy_proc_middle_U0_config_out_data_V_din,
        if_full_n => fft_config2_data_V_full_n,
        if_write => dummy_proc_middle_U0_config_out_data_V_write,
        if_dout => fft_config2_data_V_dout,
        if_empty_n => fft_config2_data_V_empty_n,
        if_read => fft_config1_1_U0_config_ch_data_V_read);

    xn2_channel_U : component fifo_w32_d1024_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => dummy_proc_middle_U0_out_r_din,
        if_full_n => xn2_channel_full_n,
        if_write => dummy_proc_middle_U0_out_r_write,
        if_dout => xn2_channel_dout,
        if_empty_n => xn2_channel_empty_n,
        if_read => fft_config1_1_U0_xn_read);

    xk2_channel_U : component fifo_w32_d1024_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => fft_config1_1_U0_xk_din,
        if_full_n => xk2_channel_full_n,
        if_write => fft_config1_1_U0_xk_write,
        if_dout => xk2_channel_dout,
        if_empty_n => xk2_channel_empty_n,
        if_read => dummy_proc_be_U0_in_r_read);

    fft_status2_data_V_U : component fifo_w8_d2_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => fft_config1_1_U0_status_data_V_din,
        if_full_n => fft_status2_data_V_full_n,
        if_write => fft_config1_1_U0_status_data_V_write,
        if_dout => fft_status2_data_V_dout,
        if_empty_n => fft_status2_data_V_empty_n,
        if_read => dummy_proc_be_U0_status_in_data_V_read);

    start_for_fft_config1_U0_U : component start_for_fft_config1_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_fft_config1_U0_din,
        if_full_n => start_for_fft_config1_U0_full_n,
        if_write => dummy_proc_fe11_U0_start_write,
        if_dout => start_for_fft_config1_U0_dout,
        if_empty_n => start_for_fft_config1_U0_empty_n,
        if_read => fft_config1_U0_ap_ready);

    start_for_dummy_proc_middle_U0_U : component start_for_dummy_proc_middle_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_dummy_proc_middle_U0_din,
        if_full_n => start_for_dummy_proc_middle_U0_full_n,
        if_write => dummy_proc_fe11_U0_start_write,
        if_dout => start_for_dummy_proc_middle_U0_dout,
        if_empty_n => start_for_dummy_proc_middle_U0_empty_n,
        if_read => dummy_proc_middle_U0_ap_ready);

    start_for_dummy_proc_be_U0_U : component start_for_dummy_proc_be_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_dummy_proc_be_U0_din,
        if_full_n => start_for_dummy_proc_be_U0_full_n,
        if_write => dummy_proc_fe11_U0_start_write,
        if_dout => start_for_dummy_proc_be_U0_dout,
        if_empty_n => start_for_dummy_proc_be_U0_empty_n,
        if_read => dummy_proc_be_U0_ap_ready);

    start_for_fft_config1_1_U0_U : component start_for_fft_config1_1_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_fft_config1_1_U0_din,
        if_full_n => start_for_fft_config1_1_U0_full_n,
        if_write => dummy_proc_middle_U0_start_write,
        if_dout => start_for_fft_config1_1_U0_dout,
        if_empty_n => start_for_fft_config1_1_U0_empty_n,
        if_read => fft_config1_1_U0_ap_ready);




    ap_done <= dummy_proc_be_U0_ap_done;
    ap_idle <= (fft_config1_U0_ap_idle and fft_config1_1_U0_ap_idle and dummy_proc_middle_U0_ap_idle and dummy_proc_fe11_U0_ap_idle and dummy_proc_be_U0_ap_idle);
    ap_ready <= dummy_proc_fe11_U0_ap_ready;

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    ap_sync_continue <= ap_const_logic_1;
    ap_sync_done <= dummy_proc_be_U0_ap_done;
    ap_sync_ready <= dummy_proc_fe11_U0_ap_ready;
    dummy_proc_be_U0_ap_continue <= ap_const_logic_1;
    dummy_proc_be_U0_ap_start <= start_for_dummy_proc_be_U0_empty_n;
    dummy_proc_be_U0_start_full_n <= ap_const_logic_1;
    dummy_proc_be_U0_start_write <= ap_const_logic_0;
    dummy_proc_fe11_U0_ap_continue <= ap_const_logic_1;
    dummy_proc_fe11_U0_ap_start <= ap_start;
    dummy_proc_fe11_U0_direction <= (0=>direction, others=>'-');
    dummy_proc_fe11_U0_start_full_n <= (start_for_fft_config1_U0_full_n and start_for_dummy_proc_middle_U0_full_n and start_for_dummy_proc_be_U0_full_n);
    dummy_proc_middle_U0_ap_continue <= ap_const_logic_1;
    dummy_proc_middle_U0_ap_start <= start_for_dummy_proc_middle_U0_empty_n;
    fft_config1_1_U0_ap_continue <= ap_const_logic_1;
    fft_config1_1_U0_ap_start <= start_for_fft_config1_1_U0_empty_n;
    fft_config1_1_U0_start_full_n <= ap_const_logic_1;
    fft_config1_1_U0_start_write <= ap_const_logic_0;
    fft_config1_U0_ap_continue <= ap_const_logic_1;
    fft_config1_U0_ap_start <= start_for_fft_config1_U0_empty_n;
    fft_config1_U0_start_full_n <= ap_const_logic_1;
    fft_config1_U0_start_write <= ap_const_logic_0;
    start_for_dummy_proc_be_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_dummy_proc_middle_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_fft_config1_1_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_fft_config1_U0_din <= (0=>ap_const_logic_1, others=>'-');
end behav;
